// packages/svelte/src/Shimmer.svelte
<script lang="ts">
  import { onMount, tick, type Snippet } from 'svelte';
  import {
    extractElementInfo,
    createResizeObserver,
    type ElementInfo,
  } from '@shimmer-from-structure/core';
  import { getShimmerConfig } from './ShimmerContext';
  import type { ShimmerProps } from './types';

  let {
    loading = true,
    shimmerColor = undefined,
    backgroundColor = undefined,
    duration = undefined,
    fallbackBorderRadius = undefined,
    children,
  }: ShimmerProps & { children: Snippet } = $props();

  let measureRef: HTMLDivElement | undefined = $state();
  let elements: ElementInfo[] = $state([]);

  const contextConfig = getShimmerConfig();

  const resolvedShimmerColor = $derived(shimmerColor ?? contextConfig.shimmerColor);
  const resolvedBackgroundColor = $derived(backgroundColor ?? contextConfig.backgroundColor);
  const resolvedDuration = $derived(duration ?? contextConfig.duration);
  const resolvedFallbackBorderRadius = $derived(
    fallbackBorderRadius ?? contextConfig.fallbackBorderRadius
  );

  let observer: MutationObserver | undefined;
  let resizeCleanup: (() => void) | undefined;

  async function measureElements() {
    if (!loading || !measureRef) return;

    // Temporarily stop observing to avoid recursion from DOM-modifying measurements
    // (e.g. extractElementInfo temporarily wrapping text in spans)
    observer?.disconnect();

    // Wait for DOM update
    await tick();

    const container = measureRef;
    const containerRect = container.getBoundingClientRect();
    const extractedElements: ElementInfo[] = [];

    Array.from(container.children).forEach((child) => {
      extractedElements.push(...extractElementInfo(child, containerRect));
    });

    elements = extractedElements;

    // Restart observation session
    if (measureRef && observer) {
      observer.observe(measureRef, {
        childList: true,
        subtree: true,
        characterData: true,
        attributes: false,
      });
    }
  }

  // Re-measure when loading state changes and manage ResizeObserver lifecycle
  $effect(() => {
    if (loading && measureRef) {
      measureElements();

      // Clean up existing ResizeObserver if any
      if (resizeCleanup) {
        resizeCleanup();
      }

      // Set up ResizeObserver for this loading session
      resizeCleanup = createResizeObserver(measureRef, measureElements);
    } else {
      // Clean up ResizeObserver when not loading
      if (resizeCleanup) {
        resizeCleanup();
        resizeCleanup = undefined;
      }
    }

    // Cleanup on effect re-run or component unmount
    return () => {
      if (resizeCleanup) {
        resizeCleanup();
        resizeCleanup = undefined;
      }
    };
  });

  onMount(() => {
    measureElements();

    if (measureRef) {
      // MutationObserver: watches for DOM content changes (new children, text changes)
      observer = new MutationObserver(() => {
        // Only observe changes in the measure container (slot content changes)
        // Don't trigger when we're not loading
        if (loading) {
          measureElements();
        }
      });

      // Only observe the slot content changes, NOT the shimmer overlay
      observer.observe(measureRef, {
        childList: true,
        subtree: true,
        characterData: true,
        attributes: false, // Don't observe attribute changes (style updates)
      });
    }

    return () => {
      observer?.disconnect();
    };
  });

  // Helper to signal content change from parent (optional)
  export function remeasure() {
    measureElements();
  }
  const styleTag = 'style';
</script>

{#if !loading}
  {@render children()}
{:else}
  <div style="position: relative;">
    <!-- Measure container with transparent text -->
    <div
      bind:this={measureRef}
      class="shimmer-measure-container"
      style="pointer-events: none;"
      aria-hidden="true"
    >
      {@render children()}
    </div>

    <!-- Shimmer overlay - isolated from mutation observer -->
    <div
      style="
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        overflow: hidden;
        pointer-events: none;
      "
    >
      <svelte:element this={styleTag}>
        {`
          @keyframes shimmer-animation {
            0% { transform: translateX(-100%); }
            100% { transform: translateX(100%); }
          }
        `}
      </svelte:element>

      {#each elements as element, index (index)}
        <div
          style="
            position: absolute;
            left: {element.x}px;
            top: {element.y}px;
            width: {element.width}px;
            height: {element.height}px;
            background-color: {resolvedBackgroundColor};
            border-radius: {element.borderRadius === '0px'
            ? resolvedFallbackBorderRadius + 'px'
            : element.borderRadius};
            overflow: hidden;
          "
        >
          <div
            style="
              position: absolute;
              top: 0;
              left: 0;
              width: 100%;
              height: 100%;
              background: linear-gradient(90deg, transparent, {resolvedShimmerColor}, transparent);
              animation: shimmer-animation {resolvedDuration}s infinite;
            "
          ></div>
        </div>
      {/each}
    </div>
  </div>
{/if}

<style>
  .shimmer-measure-container :global(*) {
    color: transparent !important;
  }
  .shimmer-measure-container :global(img),
  .shimmer-measure-container :global(svg),
  .shimmer-measure-container :global(video) {
    opacity: 0;
  }
</style>

// packages/angular/src/shimmer.component.ts
import {
  Component,
  input,
  signal,
  computed,
  effect,
  ElementRef,
  viewChild,
  AfterViewInit,
  OnDestroy,
  ChangeDetectionStrategy,
  ViewEncapsulation,
} from '@angular/core';
import { NgIf, NgFor } from '@angular/common';
import {
  extractElementInfo,
  createResizeObserver,
  type ElementInfo,
} from '@shimmer-from-structure/core';
import { injectShimmerConfig } from './shimmer-config.service';

/**
 * Shimmer component that creates loading skeleton overlays based on content structure.
 * Automatically measures projected content and creates matching shimmer blocks.
 *
 * @example
 * ```html
 * <shimmer [loading]="isLoading">
 *   <div class="card">
 *     <h2>{{ title }}</h2>
 *     <p>{{ description }}</p>
 *   </div>
 * </shimmer>
 * ```
 */
@Component({
  selector: 'shimmer',
  standalone: true,
  imports: [NgIf, NgFor],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div style="position: relative;">
      <!-- Always render content -->
      <div #measureContainer
        [class.shimmer-measure-container]="loading()"
        [attr.aria-hidden]="loading() ? 'true' : null"
        [style.pointer-events]="loading() ? 'none' : null">
        <ng-content></ng-content>
      </div>

      <!-- Shimmer overlay - only when loading -->
      @if (loading()) {
        <div
          style="
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            overflow: hidden;
            pointer-events: none;
          "
        >
          @for (element of elements(); track $index) {
            <div
              [style.position]="'absolute'"
              [style.left.px]="element.x"
              [style.top.px]="element.y"
              [style.width.px]="element.width"
              [style.height.px]="element.height"
              [style.backgroundColor]="resolvedBackgroundColor()"
              [style.borderRadius]="element.borderRadius === '0px'
                ? resolvedFallbackBorderRadius() + 'px'
                : element.borderRadius"
              [style.overflow]="'hidden'"
            >
              <div
                class="shimmer-animation-element"
                [style.background]="'linear-gradient(90deg, transparent, ' + resolvedShimmerColor() + ', transparent)'"
                [style.animationDuration]="resolvedDuration() + 's'"
              ></div>
            </div>
          }
        </div>
      }
    </div>
  `,
  styles: [`
    :host {
      display: contents;
    }

    .shimmer-measure-container * {
      color: transparent !important;
    }

    .shimmer-measure-container img,
    .shimmer-measure-container svg,
    .shimmer-measure-container video {
      opacity: 0;
    }

    .shimmer-animation-element {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      animation: shimmer-animation 1.5s infinite;
    }

    @keyframes shimmer-animation {
      0% {
        transform: translateX(-100%);
      }
      100% {
        transform: translateX(100%);
      }
    }
  `],
})
export class ShimmerComponent implements AfterViewInit, OnDestroy {
  // Inputs using Angular signals
  loading = input<boolean>(true);
  shimmerColor = input<string | undefined>(undefined);
  backgroundColor = input<string | undefined>(undefined);
  duration = input<number | undefined>(undefined);
  fallbackBorderRadius = input<number | undefined>(undefined);

  // View child reference
  measureContainer = viewChild<ElementRef<HTMLDivElement>>('measureContainer');

  // Internal state
  elements = signal<ElementInfo[]>([]);

  // Inject global config
  private contextConfig = injectShimmerConfig();

  // Resolved values (props > context > defaults)
  resolvedShimmerColor = computed(
    () => this.shimmerColor() ?? this.contextConfig.shimmerColor
  );
  resolvedBackgroundColor = computed(
    () => this.backgroundColor() ?? this.contextConfig.backgroundColor
  );
  resolvedDuration = computed(
    () => this.duration() ?? this.contextConfig.duration
  );
  resolvedFallbackBorderRadius = computed(
    () => this.fallbackBorderRadius() ?? this.contextConfig.fallbackBorderRadius
  );

  // Cleanup function for ResizeObserver
  private resizeCleanup: (() => void) | undefined;
  private mutationObserver: MutationObserver | undefined;

  constructor() {
    // Effect to re-measure when loading state changes
    effect(() => {
      const isLoading = this.loading();
      const container = this.measureContainer();

      if (isLoading && container) {
        // Defer measurement to next frame to ensure content is rendered
        requestAnimationFrame(() => this.measureElements());
      } else {
        // Cleanup when not loading
        this.cleanup();
      }
    });
  }

  ngAfterViewInit(): void {
    if (this.loading()) {
      this.setupObservers();
      this.measureElements();
    }
  }

  ngOnDestroy(): void {
    this.cleanup();
  }

  private setupObservers(): void {
    const container = this.measureContainer()?.nativeElement;
    if (!container) return;

    // Set up ResizeObserver
    this.resizeCleanup = createResizeObserver(container, () => this.measureElements());

    // Set up MutationObserver for content changes
    this.mutationObserver = new MutationObserver(() => {
      if (this.loading()) {
        this.measureElements();
      }
    });

    this.mutationObserver.observe(container, {
      childList: true,
      subtree: true,
      characterData: true,
      attributes: false,
    });
  }

  private measureElements(): void {
    const container = this.measureContainer()?.nativeElement;
    if (!container || !this.loading()) return;

    // Temporarily disconnect mutation observer to avoid recursion
    this.mutationObserver?.disconnect();

    const containerRect = container.getBoundingClientRect();
    const extractedElements: ElementInfo[] = [];

    Array.from(container.children).forEach((child) => {
      extractedElements.push(...extractElementInfo(child, containerRect));
    });

    this.elements.set(extractedElements);

    // Reconnect mutation observer
    if (this.mutationObserver && container) {
      this.mutationObserver.observe(container, {
        childList: true,
        subtree: true,
        characterData: true,
        attributes: false,
      });
    }
  }

  private cleanup(): void {
    if (this.resizeCleanup) {
      this.resizeCleanup();
      this.resizeCleanup = undefined;
    }
    if (this.mutationObserver) {
      this.mutationObserver.disconnect();
      this.mutationObserver = undefined;
    }
  }

  /**
   * Manually trigger re-measurement of elements.
   * Useful when content changes programmatically.
   */
  remeasure(): void {
    this.measureElements();
  }
}
