// packages/vue/src/Shimmer.vue
<template>
  <div v-if="!loading">
    <slot></slot>
  </div>
  <div v-else style="position: relative">
    <!-- Styles for hiding text -->
    <component :is="'style'">
      {{ measureStyles }}
    </component>

    <!-- Measure container with transparent text -->
    <div
      ref="measureRef"
      class="shimmer-measure-container"
      style="pointer-events: none"
      aria-hidden="true"
    >
      <slot :loading="true" v-bind="templateProps"></slot>
    </div>

    <!-- Shimmer overlay -->
    <div :style="overlayStyle">
      <component :is="'style'">
        {{ shimmerKeyframes }}
      </component>

      <div v-for="(element, index) in elements" :key="index" :style="getElementStyle(element)">
        <div :style="getShimmerStyle()"></div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onUnmounted, nextTick, watch } from 'vue';
import {
  extractElementInfo,
  createResizeObserver,
  type ElementInfo,
} from '@shimmer-from-structure/core';
import { useShimmerConfig } from './composables/useShimmerConfig';

interface Props {
  loading?: boolean;
  shimmerColor?: string;
  backgroundColor?: string;
  duration?: number;
  fallbackBorderRadius?: number;
  templateProps?: Record<string, unknown>;
}

const props = withDefaults(defineProps<Props>(), {
  loading: true,
});

const measureRef = ref<HTMLElement | null>(null);
const elements = ref<ElementInfo[]>([]);

// Get context values
const contextConfig = useShimmerConfig();

// Resolved configuration (props > context > defaults)
const resolvedShimmerColor = computed(() => props.shimmerColor ?? contextConfig.shimmerColor);
const resolvedBackgroundColor = computed(
  () => props.backgroundColor ?? contextConfig.backgroundColor
);
const resolvedDuration = computed(() => props.duration ?? contextConfig.duration);
const resolvedFallbackBorderRadius = computed(
  () => props.fallbackBorderRadius ?? contextConfig.fallbackBorderRadius
);

// Measurement logic
const measureElements = async () => {
  if (!props.loading || !measureRef.value) return;

  await nextTick();

  const container = measureRef.value;
  const containerRect = container.getBoundingClientRect();

  const extractedElements: ElementInfo[] = [];
  Array.from(container.children).forEach((child) => {
    extractedElements.push(...extractElementInfo(child, containerRect));
  });

  elements.value = extractedElements;
};

// Track cleanup function for ResizeObserver
let cleanupObserver: (() => void) | null = null;

// Watch for loading state changes and manage ResizeObserver lifecycle
watch(
  () => props.loading,
  async (isLoading) => {
    // Clean up existing observer when loading changes
    if (cleanupObserver) {
      cleanupObserver();
      cleanupObserver = null;
    }

    if (isLoading) {
      await measureElements();

      // Set up ResizeObserver when loading starts
      if (measureRef.value) {
        cleanupObserver = createResizeObserver(measureRef.value, measureElements);
      }
    }
  },
  { immediate: true }
);

onUnmounted(() => {
  if (cleanupObserver) {
    cleanupObserver();
  }
});

// Computed styles
const measureStyles = computed(
  () => `
  .shimmer-measure-container * {
    color: transparent !important;
  }
  .shimmer-measure-container img,
  .shimmer-measure-container svg,
  .shimmer-measure-container video {
    opacity: 0;
  }
`
);

const shimmerKeyframes = computed(
  () => `
  @keyframes shimmer {
    0% {
      transform: translateX(-100%);
    }
    100% {
      transform: translateX(100%);
    }
  }
`
);

const overlayStyle = computed(() => ({
  position: 'absolute' as const,
  top: '0',
  left: '0',
  right: '0',
  bottom: '0',
  overflow: 'hidden',
}));

const getElementStyle = (element: ElementInfo) => ({
  position: 'absolute' as const,
  left: `${element.x}px`,
  top: `${element.y}px`,
  width: `${element.width}px`,
  height: `${element.height}px`,
  backgroundColor: resolvedBackgroundColor.value,
  borderRadius:
    element.borderRadius === '0px'
      ? `${resolvedFallbackBorderRadius.value}px`
      : element.borderRadius,
  overflow: 'hidden',
});

const getShimmerStyle = () => ({
  position: 'absolute' as const,
  top: '0',
  left: '0',
  width: '100%',
  height: '100%',
  background: `linear-gradient(90deg, transparent, ${resolvedShimmerColor.value}, transparent)`,
  animation: `shimmer ${resolvedDuration.value}s infinite`,
});
</script>

// packages/svelte/src/Shimmer.svelte
<script lang="ts">
  import { onMount, tick, type Snippet } from 'svelte';
  import {
    extractElementInfo,
    createResizeObserver,
    type ElementInfo,
  } from '@shimmer-from-structure/core';
  import { getShimmerConfig } from './ShimmerContext';
  import type { ShimmerProps } from './types';

  let {
    loading = true,
    shimmerColor = undefined,
    backgroundColor = undefined,
    duration = undefined,
    fallbackBorderRadius = undefined,
    children,
  }: ShimmerProps & { children: Snippet } = $props();

  let measureRef: HTMLDivElement | undefined = $state();
  let elements: ElementInfo[] = $state([]);

  const contextConfig = getShimmerConfig();

  const resolvedShimmerColor = $derived(shimmerColor ?? contextConfig.shimmerColor);
  const resolvedBackgroundColor = $derived(backgroundColor ?? contextConfig.backgroundColor);
  const resolvedDuration = $derived(duration ?? contextConfig.duration);
  const resolvedFallbackBorderRadius = $derived(
    fallbackBorderRadius ?? contextConfig.fallbackBorderRadius
  );

  let observer: MutationObserver | undefined;
  let resizeCleanup: (() => void) | undefined;

  async function measureElements() {
    if (!loading || !measureRef) return;

    // Temporarily stop observing to avoid recursion from DOM-modifying measurements
    // (e.g. extractElementInfo temporarily wrapping text in spans)
    observer?.disconnect();

    // Wait for DOM update
    await tick();

    const container = measureRef;
    const containerRect = container.getBoundingClientRect();
    const extractedElements: ElementInfo[] = [];

    Array.from(container.children).forEach((child) => {
      extractedElements.push(...extractElementInfo(child, containerRect));
    });

    elements = extractedElements;

    // Restart observation session
    if (measureRef && observer) {
      observer.observe(measureRef, {
        childList: true,
        subtree: true,
        characterData: true,
        attributes: false,
      });
    }
  }

  // Re-measure when loading state changes and manage ResizeObserver lifecycle
  $effect(() => {
    if (loading && measureRef) {
      measureElements();

      // Clean up existing ResizeObserver if any
      if (resizeCleanup) {
        resizeCleanup();
      }

      // Set up ResizeObserver for this loading session
      resizeCleanup = createResizeObserver(measureRef, measureElements);
    } else {
      // Clean up ResizeObserver when not loading
      if (resizeCleanup) {
        resizeCleanup();
        resizeCleanup = undefined;
      }
    }

    // Cleanup on effect re-run or component unmount
    return () => {
      if (resizeCleanup) {
        resizeCleanup();
        resizeCleanup = undefined;
      }
    };
  });

  onMount(() => {
    measureElements();

    if (measureRef) {
      // MutationObserver: watches for DOM content changes (new children, text changes)
      observer = new MutationObserver(() => {
        // Only observe changes in the measure container (slot content changes)
        // Don't trigger when we're not loading
        if (loading) {
          measureElements();
        }
      });

      // Only observe the slot content changes, NOT the shimmer overlay
      observer.observe(measureRef, {
        childList: true,
        subtree: true,
        characterData: true,
        attributes: false, // Don't observe attribute changes (style updates)
      });
    }

    return () => {
      observer?.disconnect();
    };
  });

  // Helper to signal content change from parent (optional)
  export function remeasure() {
    measureElements();
  }
  const styleTag = 'style';
</script>

{#if !loading}
  {@render children()}
{:else}
  <div style="position: relative;">
    <!-- Measure container with transparent text -->
    <div
      bind:this={measureRef}
      class="shimmer-measure-container"
      style="pointer-events: none;"
      aria-hidden="true"
    >
      {@render children()}
    </div>

    <!-- Shimmer overlay - isolated from mutation observer -->
    <div
      style="
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        overflow: hidden;
        pointer-events: none;
      "
    >
      <svelte:element this={styleTag}>
        {`
          @keyframes shimmer-animation {
            0% { transform: translateX(-100%); }
            100% { transform: translateX(100%); }
          }
        `}
      </svelte:element>

      {#each elements as element, index (index)}
        <div
          style="
            position: absolute;
            left: {element.x}px;
            top: {element.y}px;
            width: {element.width}px;
            height: {element.height}px;
            background-color: {resolvedBackgroundColor};
            border-radius: {element.borderRadius === '0px'
            ? resolvedFallbackBorderRadius + 'px'
            : element.borderRadius};
            overflow: hidden;
          "
        >
          <div
            style="
              position: absolute;
              top: 0;
              left: 0;
              width: 100%;
              height: 100%;
              background: linear-gradient(90deg, transparent, {resolvedShimmerColor}, transparent);
              animation: shimmer-animation {resolvedDuration}s infinite;
            "
          ></div>
        </div>
      {/each}
    </div>
  </div>
{/if}

<style>
  .shimmer-measure-container :global(*) {
    color: transparent !important;
  }
  .shimmer-measure-container :global(img),
  .shimmer-measure-container :global(svg),
  .shimmer-measure-container :global(video) {
    opacity: 0;
  }
</style>
