// examples/svelte-example/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Shimmer } from '@shimmer-from-structure/svelte';
  import ContextExample from './ContextExample.svelte';

  // Types
  interface User {
    name: string;
    email: string;
    role: string;
    avatar: string;
    status: 'online' | 'away' | 'offline';
  }

  interface StatCard {
    label: string;
    value: string;
    change: string;
    trend: 'up' | 'down';
  }

  interface Transaction {
    id: string;
    description: string;
    amount: string;
    date: string;
    status: 'completed' | 'pending' | 'failed';
  }

  interface ActivityItem {
    id: string;
    user: string;
    action: string;
    target: string;
    time: string;
  }

  interface TeamMember {
    id: string;
    name: string;
    role: string;
    avatar: string;
  }

  interface Order {
    id: string;
    customer: string;
    product: string;
    amount: string;
    status: 'Delivered' | 'Processing' | 'Cancelled';
  }

  interface MetricCard {
    id: string;
    title: string;
    value: string;
    change: string;
    trend: 'up' | 'down';
    isLive: boolean;
  }

  interface ChartDataPoint {
    name: string;
    revenue: number;
    orders: number;
  }

  interface Notification {
    id: string;
    title: string;
    message: string;
    time: string;
    type: 'info' | 'success' | 'warning';
  }

  // Template Data
  const userTemplate: User = {
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'software Engineer',
    avatar: 'https://placeholder.photo/64',
    status: 'offline',
  };

  const statsTemplate: StatCard[] = [
    { label: 'Total Revenue', value: '$00,000', change: '+0.0%', trend: 'up' },
    { label: 'Active Users', value: '0,000', change: '+0.0%', trend: 'up' },
    { label: 'Conversion', value: '0.0%', change: '-0.0%', trend: 'down' },
    { label: 'Avg. Order', value: '$000', change: '+0.0%', trend: 'up' },
  ];

  const transactionsTemplate: Transaction[] = Array(4)
    .fill(null)
    .map((_, i) => ({
      id: `${i}`,
      description: 'Loading transaction...',
      amount: '$0.00',
      date: 'Jan 00',
      status: 'pending' as const,
    }));

  const activityTemplate: ActivityItem[] = Array(3)
    .fill(null)
    .map((_, i) => ({
      id: `${i}`,
      user: 'Loading...',
      action: 'performed',
      target: 'an action',
      time: '0m ago',
    }));

  const teamTemplate: TeamMember[] = Array(4)
    .fill(null)
    .map((_, i) => ({
      id: `${i}`,
      name: 'Loading...',
      role: 'Role',
      avatar: 'https://placeholder.photo/40',
    }));

  const ordersTemplate: Order[] = Array(5)
    .fill(null)
    .map((_, i) => ({
      id: `${i}`,
      customer: 'Loading Name...',
      product: 'Loading Product...',
      amount: '$000.00',
      status: 'Processing' as const,
    }));

  const chartTemplate: ChartDataPoint[] = [
    { name: 'Mon', revenue: 3000, orders: 30 },
    { name: 'Tue', revenue: 4500, orders: 45 },
    { name: 'Wed', revenue: 3800, orders: 38 },
    { name: 'Thu', revenue: 5200, orders: 52 },
    { name: 'Fri', revenue: 6100, orders: 61 },
    { name: 'Sat', revenue: 7000, orders: 70 },
    { name: 'Sun', revenue: 5500, orders: 55 },
  ];

  const notificationsTemplate: Notification[] = [
    {
      id: '1',
      title: 'Loading...',
      message: 'Notification message loading...',
      time: '0m',
      type: 'info',
    },
    {
      id: '2',
      title: 'Loading...',
      message: 'Notification message loading...',
      time: '0m',
      type: 'info',
    },
    {
      id: '3',
      title: 'Loading...',
      message: 'Notification message loading...',
      time: '0m',
      type: 'info',
    },
  ];

  // Real Data
  const realUser: User = {
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'Product Manager',
    avatar: 'https://i.pravatar.cc/64?img=5',
    status: 'online',
  };

  const realStats: StatCard[] = [
    { label: 'Total Revenue', value: '$48,352', change: '+12.5%', trend: 'up' },
    { label: 'Active Users', value: '2,847', change: '+8.2%', trend: 'up' },
    { label: 'Conversion', value: '3.24%', change: '-0.4%', trend: 'down' },
    { label: 'Avg. Order', value: '$284', change: '+5.7%', trend: 'up' },
  ];

  const realTransactions: Transaction[] = [
    {
      id: '1',
      description: 'Premium Subscription',
      amount: '$99.00',
      date: 'Jan 20',
      status: 'completed',
    },
    {
      id: '2',
      description: 'API Credits Purchase',
      amount: '$250.00',
      date: 'Jan 19',
      status: 'completed',
    },
    {
      id: '3',
      description: 'Team License Upgrade',
      amount: '$499.00',
      date: 'Jan 18',
      status: 'pending',
    },
    {
      id: '4',
      description: 'Support Add-on',
      amount: '$49.00',
      date: 'Jan 17',
      status: 'completed',
    },
  ];

  const realActivity: ActivityItem[] = [
    {
      id: '1',
      user: 'Mike Chen',
      action: 'deployed',
      target: 'v2.4.1 to production',
      time: '5m ago',
    },
    {
      id: '2',
      user: 'Emily Davis',
      action: 'approved',
      target: 'design review for Dashboard',
      time: '23m ago',
    },
    { id: '3', user: 'Alex Rivera', action: 'commented on', target: 'Issue #847', time: '1h ago' },
  ];

  const realTeam: TeamMember[] = [
    {
      id: '1',
      name: 'Mike Chen',
      role: 'Lead Developer',
      avatar: 'https://i.pravatar.cc/40?img=11',
    },
    { id: '2', name: 'Emily Davis', role: 'UX Designer', avatar: 'https://i.pravatar.cc/40?img=9' },
    {
      id: '3',
      name: 'Alex Rivera',
      role: 'Backend Engineer',
      avatar: 'https://i.pravatar.cc/40?img=12',
    },
    { id: '4', name: 'Jordan Lee', role: 'DevOps', avatar: 'https://i.pravatar.cc/40?img=15' },
  ];

  const realOrders: Order[] = [
    {
      id: '101',
      customer: 'Alice Freeman',
      product: 'Pro Plan (Monthly)',
      amount: '$29.00',
      status: 'Delivered',
    },
    {
      id: '102',
      customer: 'Bob Smith',
      product: 'Enterprise License',
      amount: '$499.00',
      status: 'Processing',
    },
    {
      id: '103',
      customer: 'Charlie Brown',
      product: 'Basic Plan (Yearly)',
      amount: '$99.00',
      status: 'Cancelled',
    },
    {
      id: '104',
      customer: 'David Wilson',
      product: 'Pro Plan (monthly)',
      amount: '$29.00',
      status: 'Delivered',
    },
    {
      id: '105',
      customer: 'Eva Green',
      product: 'Consulting Hour',
      amount: '$150.00',
      status: 'Delivered',
    },
  ];

  const realChartData: ChartDataPoint[] = [
    { name: 'Mon', revenue: 4200, orders: 42 },
    { name: 'Tue', revenue: 5800, orders: 58 },
    { name: 'Wed', revenue: 4900, orders: 49 },
    { name: 'Thu', revenue: 7200, orders: 72 },
    { name: 'Fri', revenue: 8400, orders: 84 },
    { name: 'Sat', revenue: 9100, orders: 91 },
    { name: 'Sun', revenue: 6800, orders: 68 },
  ];

  const realNotifications: Notification[] = [
    {
      id: '1',
      title: 'New Comment',
      message: 'Sarah commented on your pull request #42',
      time: '2m',
      type: 'info',
    },
    {
      id: '2',
      title: 'Build Passed',
      message: 'CI pipeline completed successfully',
      time: '15m',
      type: 'success',
    },
    {
      id: '3',
      title: 'Security Alert',
      message: 'New login detected from Safari on macOS',
      time: '1h',
      type: 'warning',
    },
  ];

  const metricCardsTemplate: MetricCard[] = [
    { id: '1', title: 'API Requests', value: '0.0k/s', change: '+0.0%', trend: 'up', isLive: true },
    { id: '2', title: 'Error Rate', value: '0.00%', change: '-0.00%', trend: 'up', isLive: true },
    { id: '3', title: 'Uptime', value: '00.00%', change: '+0.00%', trend: 'up', isLive: false },
  ];

  const realMetricCards: MetricCard[] = [
    { id: '1', title: 'API Requests', value: '12.4k/s', change: '+3.2%', trend: 'up', isLive: true },
    { id: '2', title: 'Error Rate', value: '0.08%', change: '-0.01%', trend: 'up', isLive: true },
    { id: '3', title: 'Uptime', value: '99.98%', change: '+0.01%', trend: 'up', isLive: false },
  ];

  // State
  let loadingUser = true;
  let loadingStats = true;
  let loadingTransactions = true;
  let loadingActivity = true;
  let loadingTeam = true;
  let loadingOrders = true;
  let loadingChart = true;
  let loadingNotifications = true;
  let loadingContextExample = true;
  let loadingAttributesDemo = true;

  let user: User | null = null;
  let stats: StatCard[] | null = null;
  let transactions: Transaction[] | null = null;
  let orders: Order[] | null = null;
  let activity: ActivityItem[] | null = null;
  let team: TeamMember[] | null = null;
  let chartData: ChartDataPoint[] | null = null;
  let notifications: Notification[] | null = null;
  let contextData: TeamMember[] | null = null;
  let attributesDemoData: MetricCard[] | null = null;

  function loadData() {
    loadingUser = true;
    loadingStats = true;
    loadingTransactions = true;
    loadingActivity = true;
    loadingTeam = true;
    loadingOrders = true;
    loadingChart = true;
    loadingNotifications = true;
    loadingContextExample = true;
    loadingAttributesDemo = true;

    user = null;
    stats = null;
    transactions = null;
    orders = null;
    activity = null;
    team = null;
    chartData = null;
    notifications = null;
    contextData = null;
    attributesDemoData = null;

    // Simulate timeouts matching React example
    setTimeout(() => {
      user = realUser;
      loadingUser = false;
    }, 8000);
    setTimeout(() => {
      stats = realStats;
      loadingStats = false;
    }, 12000);
    setTimeout(() => {
      chartData = realChartData;
      loadingChart = false;
    }, 14000);
    setTimeout(() => {
      team = realTeam;
      loadingTeam = false;
    }, 16000);
    setTimeout(() => {
      orders = realOrders;
      loadingOrders = false;
    }, 18000);
    setTimeout(() => {
      activity = realActivity;
      loadingActivity = false;
    }, 20000);
    setTimeout(() => {
      transactions = realTransactions;
      loadingTransactions = false;
    }, 25000);
    // Async component demo - simulate network delay
    setTimeout(() => {
      notifications = realNotifications;
      loadingNotifications = false;
    }, 30000);
    // Context example loads extra slow
    setTimeout(() => {
      contextData = realTeam.slice(0, 2);
      loadingContextExample = false;
    }, 4000);
    // Attribute controls demo
    setTimeout(() => {
      attributesDemoData = realMetricCards;
      loadingAttributesDemo = false;
    }, 6000);
  }

  onMount(() => {
    loadData();
  });
</script>

<div class="dashboard">
  <header class="dashboard-header">
    <div class="header-content">
      <h1>Shimmer From Structure (Svelte)</h1>
      <p>Real-world dashboard demo with independent loading states</p>
    </div>
    <button class="reload-btn" on:click={loadData}> ↻ Reload Demo </button>
  </header>

  <!-- User Profile Section -->
  <section class="dashboard-section">
    <Shimmer loading={loadingUser}>
      {@const u = user || userTemplate}
      <div class="user-profile">
        <img src={u.avatar} alt={u.name} class="user-avatar" />
        <div class="user-info">
          <h2>{u.name}</h2>
          <p class="user-email">{u.email}</p>
          <span class={`user-status ${u.status}`}>{u.role}</span>
        </div>
        <div class={`status-indicator ${u.status}`}>
          <span class="status-dot"></span>
          {u.status}
        </div>
      </div>
    </Shimmer>
  </section>

  <!-- Stats Section -->
  <section class="dashboard-section">
    <Shimmer loading={loadingStats}>
      <div class="stats-grid">
        {#each stats || statsTemplate as stat}
          <div class="stat-card">
            <p class="stat-label">{stat.label}</p>
            <h3 class="stat-value">{stat.value}</h3>
            <span class={`stat-change ${stat.trend}`}>
              {stat.trend === 'up' ? '↑' : '↓'}
              {stat.change}
            </span>
          </div>
        {/each}
      </div>
    </Shimmer>
  </section>

  <!-- Async Loading Demo (Svelte equivalent of Suspense) -->
  <section class="dashboard-section suspense-section">
    <div class="suspense-label">⚡ Async Component Loading Demo</div>
    <Shimmer
      loading={loadingNotifications}
    >
      <div class="notifications-panel">
        <h3 class="section-title">🔔 Notifications (Async Demo)</h3>
        <div class="notifications-list">
          {#each notifications || notificationsTemplate as notif}
            <div class={`notification-item ${notif.type}`}>
              <div class="notification-header">
                <span class="notification-title">{notif.title}</span>
                <span class="notification-time">{notif.time}</span>
              </div>
              <p class="notification-message">{notif.message}</p>
            </div>
          {/each}
        </div>
      </div>
    </Shimmer>
  </section>

  <!-- Orders Table Section -->
  <section class="dashboard-section">
    <Shimmer loading={loadingOrders}>
      <div class="orders-table-container">
        <h3 class="section-title">Recent Orders</h3>
        <table
          class="orders-table"
          style="width: 100%; border-collapse: collapse; table-layout: fixed;"
        >
          <thead>
            <tr style="border-bottom: 1px solid #eee; text-align: left;">
              <th style="padding: 12px 16px; width: 25%;">Customer</th>
              <th style="padding: 12px 16px; width: 40%;">Product</th>
              <th style="padding: 12px 16px; width: 20%;">Amount</th>
              <th style="padding: 12px 16px; width: 15%;">Status</th>
            </tr>
          </thead>
          <tbody>
            {#each orders || ordersTemplate as order}
              <tr style="border-bottom: 1px solid #f9f9f9;">
                <td style="padding: 12px 16px; font-weight: 500;">{order.customer}</td>
                <td style="padding: 12px 16px; color: #666;">{order.product}</td>
                <td style="padding: 12px 16px; font-weight: 600;">{order.amount}</td>
                <td style="padding: 12px 16px;">
                  <span
                    style="
                      display: inline-block;
                      padding: 4px 8px;
                      border-radius: 12px;
                      font-size: 0.85em;
                      background: {order.status === 'Delivered'
                      ? '#dcfce7'
                      : order.status === 'Processing'
                        ? '#dbeafe'
                        : '#fee2e2'};
                      color: {order.status === 'Delivered'
                      ? '#166534'
                      : order.status === 'Processing'
                        ? '#1e40af'
                        : '#991b1b'};
                    "
                  >
                    {order.status}
                  </span>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    </Shimmer>
  </section>

  <!-- Revenue Chart Section -->
  <section class="dashboard-section">
    <Shimmer loading={loadingChart}>
      <div class="revenue-chart">
        <h3 class="section-title">Weekly Revenue</h3>
        <div class="chart-container" style="height: 250px; width: 100%; position: relative;">
          {#if chartData || chartTemplate}
            {@const data = chartData || chartTemplate}
            {@const maxRevenue = Math.max(...data.map((d) => d.revenue))}
            {@const maxOrders = Math.max(...data.map((d) => d.orders))}

            <svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none">
              <defs>
                <linearGradient id="colorRevenue" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stop-color="#14b8a6" stop-opacity="0.3" />
                  <stop offset="95%" stop-color="#14b8a6" stop-opacity="0" />
                </linearGradient>
                <linearGradient id="colorOrders" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stop-color="#06b6d4" stop-opacity="0.3" />
                  <stop offset="95%" stop-color="#06b6d4" stop-opacity="0" />
                </linearGradient>
              </defs>

              <!-- Grid lines -->
              {#each [0, 25, 50, 75, 100] as tick}
                <line
                  x1="0"
                  y1={tick}
                  x2="100"
                  y2={tick}
                  stroke="rgba(255,255,255,0.1)"
                  stroke-width="0.5"
                />
              {/each}

              <!-- Revenue Area -->
              <path
                d={`M0,100 ${data.map((d, i) => `L${(i / (data.length - 1)) * 100},${100 - (d.revenue / maxRevenue) * 90}`).join(' ')} L100,100 Z`}
                fill="url(#colorRevenue)"
                stroke="none"
              />
              <path
                d={`M0,${100 - (data[0].revenue / maxRevenue) * 90} ${data.map((d, i) => `L${(i / (data.length - 1)) * 100},${100 - (d.revenue / maxRevenue) * 90}`).join(' ')}`}
                fill="none"
                stroke="#14b8a6"
                stroke-width="1"
              />

              <!-- Orders Area (Normalizing to same height for visualization) -->
              <path
                d={`M0,100 ${data.map((d, i) => `L${(i / (data.length - 1)) * 100},${100 - (d.orders / maxOrders) * 70}`).join(' ')} L100,100 Z`}
                fill="url(#colorOrders)"
                stroke="none"
              />
              <path
                d={`M0,${100 - (data[0].orders / maxOrders) * 70} ${data.map((d, i) => `L${(i / (data.length - 1)) * 100},${100 - (d.orders / maxOrders) * 70}`).join(' ')}`}
                fill="none"
                stroke="#06b6d4"
                stroke-width="1"
              />
            </svg>

            <!-- X Axis Labels -->
            <div
              style="display: flex; justify-content: space-between; margin-top: 5px; color: rgba(255,255,255,0.5); font-size: 12px;"
            >
              {#each data as point}
                <span>{point.name}</span>
              {/each}
            </div>
          {/if}
        </div>
      </div>
    </Shimmer>
  </section>

  <!-- Main Content Grid -->
  <div class="content-grid">
    <!-- Transactions -->
    <section class="dashboard-section">
      <Shimmer loading={loadingTransactions}>
        <div class="transactions-list">
          <h3 class="section-title">Recent Transactions</h3>
          <div class="transactions">
            {#each transactions || transactionsTemplate as tx}
              <div class="transaction-item">
                <div class="tx-info">
                  <p class="tx-description">{tx.description}</p>
                  <span class="tx-date">{tx.date}</span>
                </div>
                <div class="tx-right">
                  <span class="tx-amount">{tx.amount}</span>
                  <span class={`tx-status ${tx.status}`}>{tx.status}</span>
                </div>
              </div>
            {/each}
          </div>
        </div>
      </Shimmer>
    </section>

    <!-- Right Sidebar -->
    <div class="sidebar">
      <!-- Activity Feed -->
      <section class="dashboard-section">
        <Shimmer loading={loadingActivity}>
          <div class="activity-feed">
            <h3 class="section-title">Recent Activity</h3>
            <div class="activities">
              {#each activity || activityTemplate as act}
                <div class="activity-item">
                  <div class="activity-dot"></div>
                  <div class="activity-content">
                    <p>
                      <strong>{act.user}</strong>
                      {act.action}{' '}
                      <span class="activity-target">{act.target}</span>
                    </p>
                    <span class="activity-time">{act.time}</span>
                  </div>
                </div>
              {/each}
            </div>
          </div>
        </Shimmer>
      </section>

      <!-- Team Members -->
      <section class="dashboard-section">
        <Shimmer loading={loadingTeam}>
          <div class="team-members">
            <h3 class="section-title">Team</h3>
            <div class="members-grid">
              {#each team || teamTemplate as member}
                <div class="member-card">
                  <img src={member.avatar} alt={member.name} class="member-avatar" />
                  <p class="member-name">{member.name}</p>
                  <span class="member-role">{member.role}</span>
                </div>
              {/each}
            </div>
          </div>
        </Shimmer>
      </section>
    </div>
  </div>

  <!-- Context API Example -->
  <section class="dashboard-section context-section" style="margin-top: 2rem;">
    <h3 class="section-title">🎨 Context API Example (Custom Theme)</h3>
    <p style="margin-bottom: 1rem; color: #888;">
      This section uses <code>setShimmerConfig</code> during initialization to apply a global blue theme
      below.
    </p>

    <ContextExample {loadingContextExample} {contextData} {teamTemplate} />
  </section>

  <!-- HTML Attribute Controls Demo -->
  <section class="dashboard-section" style="margin-top: 2rem;">
    <h3 class="section-title">🎛️ HTML Attribute Controls</h3>
    <p class="attributes-demo-description">
      Use <code>data-shimmer-ignore</code> to exclude an element and its children entirely.
      Use <code>data-shimmer-no-children</code> to capture an element as a single shimmer block.
    </p>
    <Shimmer loading={loadingAttributesDemo}>
      <div class="attributes-demo-grid">
        {#each attributesDemoData || metricCardsTemplate as card, i}
          <div class="attr-card">
            <div class="attr-card-header">
              <span class="attr-card-title">{card.title}</span>
              <!-- data-shimmer-ignore: badge is excluded from shimmer entirely -->
              {#if card.isLive}
                <span class="live-badge" data-shimmer-ignore="">● LIVE</span>
              {/if}
            </div>

            <!-- data-shimmer-no-children (card 2 only): whole block is one shimmer rect -->
            {#if i === 1}
              <div class="attr-card-metric" data-shimmer-no-children="">
                <span class="attr-metric-value">{card.value}</span>
                <span class="attr-metric-change {card.trend}">
                  {card.trend === 'up' ? '↑' : '↓'} {card.change}
                </span>
              </div>
            {:else}
              <div class="attr-card-metric">
                <span class="attr-metric-value">{card.value}</span>
                <span class="attr-metric-change {card.trend}">
                  {card.trend === 'up' ? '↑' : '↓'} {card.change}
                </span>
              </div>
            {/if}

            <p class="attr-card-note">
              {#if i === 0}"LIVE" badge skipped via data-shimmer-ignore
              {:else if i === 1}Metric block is one shimmer via data-shimmer-no-children
              {:else}Normal shimmer (no attributes)
              {/if}
            </p>
          </div>
        {/each}
      </div>
    </Shimmer>
  </section>

  <!-- Footer -->
  <footer class="dashboard-footer">
    <p>
      Each section loads independently with its own shimmer effect.
      <br />
      Mock data is used to generate the skeleton structure.
    </p>
  </footer>
</div>

<style>
  /* Component styles inherit from main.css */
</style>

// examples/angular-example/src/app/app.component.ts
import { Component, signal, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ShimmerComponent } from '@shimmer-from-structure/angular';

// =============================================================================
// TYPES
// =============================================================================

interface User {
  name: string;
  email: string;
  role: string;
  avatar: string;
  status: 'online' | 'away' | 'offline';
}

interface StatCard {
  label: string;
  value: string;
  change: string;
  trend: 'up' | 'down';
}

interface Transaction {
  id: string;
  description: string;
  amount: string;
  date: string;
  status: 'completed' | 'pending' | 'failed';
}

interface ActivityItem {
  id: string;
  user: string;
  action: string;
  target: string;
  time: string;
}

interface TeamMember {
  id: string;
  name: string;
  role: string;
  avatar: string;
}

interface ChartDataPoint {
  name: string;
  revenue: number;
  orders: number;
}

interface Order {
  id: string;
  customer: string;
  product: string;
  amount: string;
  status: 'Delivered' | 'Processing' | 'Cancelled';
}

interface MetricCard {
  id: string;
  title: string;
  value: string;
  change: string;
  trend: 'up' | 'down';
  isLive: boolean;
}

interface Notification {
  id: string;
  title: string;
  message: string;
  time: string;
  type: 'info' | 'success' | 'warning';
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, ShimmerComponent],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit, OnDestroy {
  // Loading states
  loadingUser = signal(true);
  loadingStats = signal(true);
  loadingTransactions = signal(true);
  loadingActivity = signal(true);
  loadingTeam = signal(true);
  loadingOrders = signal(true);
  loadingChart = signal(true);
  loadingNotifications = signal(true);
  loadingContextExample = signal(true);
  loadingAttributesDemo = signal(true);

  // Data signals
  user = signal<User | null>(null);
  stats = signal<StatCard[] | null>(null);
  transactions = signal<Transaction[] | null>(null);
  orders = signal<Order[] | null>(null);
  activity = signal<ActivityItem[] | null>(null);
  team = signal<TeamMember[] | null>(null);
  chartData = signal<ChartDataPoint[] | null>(null);
  notifications = signal<Notification[] | null>(null);
  contextData = signal<TeamMember[] | null>(null);
  attributesDemoData = signal<MetricCard[] | null>(null);

  // Template data
  metricCardsTemplate: MetricCard[] = [
    { id: '1', title: 'API Requests', value: '0.0k/s', change: '+0.0%', trend: 'up', isLive: true },
    { id: '2', title: 'Error Rate', value: '0.00%', change: '-0.00%', trend: 'up', isLive: true },
    { id: '3', title: 'Uptime', value: '00.00%', change: '+0.00%', trend: 'up', isLive: false },
  ];

  realMetricCards: MetricCard[] = [
    {
      id: '1',
      title: 'API Requests',
      value: '12.4k/s',
      change: '+3.2%',
      trend: 'up',
      isLive: true,
    },
    { id: '2', title: 'Error Rate', value: '0.08%', change: '-0.01%', trend: 'up', isLive: true },
    { id: '3', title: 'Uptime', value: '99.98%', change: '+0.01%', trend: 'up', isLive: false },
  ];

  userTemplate: User = {
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'Software Engineer',
    avatar: 'https://placeholder.photo/64',
    status: 'offline',
  };

  statsTemplate: StatCard[] = [
    { label: 'Total Revenue', value: '$00,000', change: '+0.0%', trend: 'up' },
    { label: 'Active Users', value: '0,000', change: '+0.0%', trend: 'up' },
    { label: 'Conversion', value: '0.0%', change: '-0.0%', trend: 'down' },
    { label: 'Avg. Order', value: '$000', change: '+0.0%', trend: 'up' },
  ];

  transactionsTemplate: Transaction[] = [
    {
      id: '1',
      description: 'Loading transaction...',
      amount: '$0.00',
      date: 'Jan 00',
      status: 'pending',
    },
    {
      id: '2',
      description: 'Loading transaction...',
      amount: '$0.00',
      date: 'Jan 00',
      status: 'pending',
    },
    {
      id: '3',
      description: 'Loading transaction...',
      amount: '$0.00',
      date: 'Jan 00',
      status: 'pending',
    },
    {
      id: '4',
      description: 'Loading transaction...',
      amount: '$0.00',
      date: 'Jan 00',
      status: 'pending',
    },
  ];

  activityTemplate: ActivityItem[] = [
    { id: '1', user: 'Loading...', action: 'performed', target: 'an action', time: '0m ago' },
    { id: '2', user: 'Loading...', action: 'performed', target: 'an action', time: '0m ago' },
    { id: '3', user: 'Loading...', action: 'performed', target: 'an action', time: '0m ago' },
  ];

  teamTemplate: TeamMember[] = [
    { id: '1', name: 'Loading...', role: 'Role', avatar: 'https://placeholder.photo/40' },
    {
      id: '2',
      name: 'Loading...',
      role: 'Lead Developer',
      avatar: 'https://placeholder.photo/40',
    },
    { id: '3', name: 'Loading...', role: 'Role', avatar: 'https://placeholder.photo/40' },
    {
      id: '4',
      name: 'Loading...',
      role: 'Backend Developer',
      avatar: 'https://placeholder.photo/40',
    },
  ];

  ordersTemplate: Order[] = [
    {
      id: '1',
      customer: 'Loading Name...',
      product: 'Loading Product...',
      amount: '$000.00',
      status: 'Processing',
    },
    {
      id: '2',
      customer: 'Loading Name...',
      product: 'Loading Product...',
      amount: '$000.00',
      status: 'Processing',
    },
    {
      id: '3',
      customer: 'Loading Name...',
      product: 'Loading Product...',
      amount: '$000.00',
      status: 'Processing',
    },
    {
      id: '4',
      customer: 'Loading Name...',
      product: 'Loading Product...',
      amount: '$000.00',
      status: 'Processing',
    },
    {
      id: '5',
      customer: 'Loading Name...',
      product: 'Loading Product...',
      amount: '$000.00',
      status: 'Processing',
    },
  ];

  chartTemplate: ChartDataPoint[] = [
    { name: 'Mon', revenue: 3000, orders: 30 },
    { name: 'Tue', revenue: 4500, orders: 45 },
    { name: 'Wed', revenue: 3800, orders: 38 },
    { name: 'Thu', revenue: 5200, orders: 52 },
    { name: 'Fri', revenue: 6100, orders: 61 },
    { name: 'Sat', revenue: 7000, orders: 70 },
    { name: 'Sun', revenue: 5500, orders: 55 },
  ];

  notificationsTemplate: Notification[] = [
    {
      id: '1',
      title: 'Loading...',
      message: 'Notification message loading...',
      time: '0m',
      type: 'info',
    },
    {
      id: '2',
      title: 'Loading...',
      message: 'Notification message loading...',
      time: '0m',
      type: 'info',
    },
    {
      id: '3',
      title: 'Loading...',
      message: 'Notification message loading...',
      time: '0m',
      type: 'info',
    },
  ];

  // Real data
  realUser: User = {
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'Product Manager',
    avatar: 'https://i.pravatar.cc/64?img=5',
    status: 'online',
  };

  realStats: StatCard[] = [
    { label: 'Total Revenue', value: '$48,352', change: '+12.5%', trend: 'up' },
    { label: 'Active Users', value: '2,847', change: '+8.2%', trend: 'up' },
    { label: 'Conversion', value: '3.24%', change: '-0.4%', trend: 'down' },
    { label: 'Avg. Order', value: '$284', change: '+5.7%', trend: 'up' },
  ];

  realTransactions: Transaction[] = [
    {
      id: '1',
      description: 'Premium Subscription',
      amount: '$99.00',
      date: 'Jan 20',
      status: 'completed',
    },
    {
      id: '2',
      description: 'API Credits Purchase',
      amount: '$250.00',
      date: 'Jan 19',
      status: 'completed',
    },
    {
      id: '3',
      description: 'Team License Upgrade',
      amount: '$499.00',
      date: 'Jan 18',
      status: 'pending',
    },
    {
      id: '4',
      description: 'Support Add-on',
      amount: '$49.00',
      date: 'Jan 17',
      status: 'completed',
    },
  ];

  realActivity: ActivityItem[] = [
    {
      id: '1',
      user: 'Mike Chen',
      action: 'deployed',
      target: 'v2.4.1 to production',
      time: '5m ago',
    },
    {
      id: '2',
      user: 'Emily Davis',
      action: 'approved',
      target: 'design review for Dashboard',
      time: '23m ago',
    },
    { id: '3', user: 'Alex Rivera', action: 'commented on', target: 'Issue #847', time: '1h ago' },
  ];

  realTeam: TeamMember[] = [
    {
      id: '1',
      name: 'Mike Chen',
      role: 'Lead Developer',
      avatar: 'https://i.pravatar.cc/40?img=11',
    },
    { id: '2', name: 'Emily Davis', role: 'UX Designer', avatar: 'https://i.pravatar.cc/40?img=9' },
    {
      id: '3',
      name: 'Alex Rivera',
      role: 'Backend Engineer',
      avatar: 'https://i.pravatar.cc/40?img=12',
    },
    { id: '4', name: 'Jordan Lee', role: 'DevOps', avatar: 'https://i.pravatar.cc/40?img=15' },
  ];

  realOrders: Order[] = [
    {
      id: '101',
      customer: 'Alice Freeman',
      product: 'Pro Plan (Monthly)',
      amount: '$29.00',
      status: 'Delivered',
    },
    {
      id: '102',
      customer: 'Bob Smith',
      product: 'Enterprise License',
      amount: '$499.00',
      status: 'Processing',
    },
    {
      id: '103',
      customer: 'Charlie Brown',
      product: 'Basic Plan (Yearly)',
      amount: '$99.00',
      status: 'Cancelled',
    },
    {
      id: '104',
      customer: 'David Wilson',
      product: 'Pro Plan (Monthly)',
      amount: '$29.00',
      status: 'Delivered',
    },
    {
      id: '105',
      customer: 'Eva Green',
      product: 'Consulting Hour',
      amount: '$150.00',
      status: 'Delivered',
    },
  ];

  realChartData: ChartDataPoint[] = [
    { name: 'Mon', revenue: 4200, orders: 42 },
    { name: 'Tue', revenue: 5800, orders: 58 },
    { name: 'Wed', revenue: 4900, orders: 49 },
    { name: 'Thu', revenue: 7200, orders: 72 },
    { name: 'Fri', revenue: 8400, orders: 84 },
    { name: 'Sat', revenue: 9100, orders: 91 },
    { name: 'Sun', revenue: 6800, orders: 68 },
  ];

  realNotifications: Notification[] = [
    {
      id: '1',
      title: 'New Comment',
      message: 'Sarah commented on your pull request #42',
      time: '2m',
      type: 'info',
    },
    {
      id: '2',
      title: 'Build Passed',
      message: 'CI pipeline completed successfully',
      time: '15m',
      type: 'success',
    },
    {
      id: '3',
      title: 'Security Alert',
      message: 'New login detected from Safari on macOS',
      time: '1h',
      type: 'warning',
    },
  ];

  private timeouts: number[] = [];

  ngOnInit() {
    console.log('AppComponent ngOnInit called');
    console.log('Initial loading states:', {
      user: this.loadingUser(),
      stats: this.loadingStats(),
      transactions: this.loadingTransactions(),
    });
    this.loadData();
  }

  ngOnDestroy() {
    this.timeouts.forEach(clearTimeout);
  }

  loadData() {
    console.log('loadData() called - setting up timeouts');

    // User loads first (fast)
    this.timeouts.push(
      window.setTimeout(() => {
        console.log('User timeout fired - setting loading to false');
        this.user.set(this.realUser);
        this.loadingUser.set(false);
        console.log('loadingUser is now:', this.loadingUser());
      }, 4800)
    );

    // Stats load second
    this.timeouts.push(
      window.setTimeout(() => {
        this.stats.set(this.realStats);
        this.loadingStats.set(false);
      }, 8200)
    );

    // Chart loads third
    this.timeouts.push(
      window.setTimeout(() => {
        this.chartData.set(this.realChartData);
        this.loadingChart.set(false);
      }, 5400)
    );

    // Team loads fourth
    this.timeouts.push(
      window.setTimeout(() => {
        this.team.set(this.realTeam);
        this.loadingTeam.set(false);
      }, 4600)
    );

    // Activity loads fifth
    this.timeouts.push(
      window.setTimeout(() => {
        this.activity.set(this.realActivity);
        this.loadingActivity.set(false);
      }, 8000)
    );

    // Transactions load last
    this.timeouts.push(
      window.setTimeout(() => {
        this.transactions.set(this.realTransactions);
        this.loadingTransactions.set(false);
      }, 9500)
    );

    // Orders load independently
    this.timeouts.push(
      window.setTimeout(() => {
        this.orders.set(this.realOrders);
        this.loadingOrders.set(false);
      }, 7800)
    );

    // Notifications (delayed like lazy loading)
    this.timeouts.push(
      window.setTimeout(() => {
        this.notifications.set(this.realNotifications);
        this.loadingNotifications.set(false);
      }, 8000)
    );

    // Context Example loads extra slow
    this.timeouts.push(
      window.setTimeout(() => {
        this.contextData.set(this.realTeam.slice(0, 2));
        this.loadingContextExample.set(false);
      }, 9000)
    );

    // Attribute controls demo
    this.timeouts.push(
      window.setTimeout(() => {
        this.attributesDemoData.set(this.realMetricCards);
        this.loadingAttributesDemo.set(false);
      }, 6000)
    );
  }

  handleReload() {
    // Reset all states
    this.loadingUser.set(true);
    this.loadingStats.set(true);
    this.loadingChart.set(true);
    this.loadingTransactions.set(true);
    this.loadingActivity.set(true);
    this.loadingTeam.set(true);
    this.loadingOrders.set(true);
    this.loadingNotifications.set(true);
    this.loadingContextExample.set(true);
    this.loadingAttributesDemo.set(true);

    this.user.set(null);
    this.stats.set(null);
    this.chartData.set(null);
    this.transactions.set(null);
    this.orders.set(null);
    this.activity.set(null);
    this.team.set(null);
    this.notifications.set(null);
    this.contextData.set(null);
    this.attributesDemoData.set(null);

    // Clear existing timeouts
    this.timeouts.forEach(clearTimeout);
    this.timeouts = [];

    // Reload data
    this.loadData();
  }

  getChartHeight(data: ChartDataPoint[], maxHeight: number): number {
    const maxRevenue = Math.max(...data.map((d) => d.revenue));
    return maxHeight * (maxRevenue / 10000);
  }
}

<div class="dashboard">
  <!-- Header -->
  <header class="dashboard-header">
    <div class="header-content">
      <h1>Shimmer From Structure</h1>
      <p>Real-world dashboard demo with independent loading states</p>
    </div>
    <button class="reload-btn" (click)="handleReload()">↻ Reload Demo</button>
  </header>

  <!-- User Profile Section -->
  <section class="dashboard-section">
    <shimmer
      [loading]="loadingUser()"
      shimmerColor="rgba(139, 92, 246, 0.4)"
      backgroundColor="rgba(139, 92, 246, 0.1)"
    >
      <div class="user-profile">
        <img
          [src]="(user() || userTemplate).avatar"
          [alt]="(user() || userTemplate).name"
          class="user-avatar"
        />
        <div class="user-info">
          <h2>{{ (user() || userTemplate).name }}</h2>
          <p class="user-email">{{ (user() || userTemplate).email }}</p>
          <span class="user-status">{{ (user() || userTemplate).role }}</span>
        </div>
        <div
          class="status-indicator"
          [class.online]="(user() || userTemplate).status === 'online'"
          [class.away]="(user() || userTemplate).status === 'away'"
        >
          <span class="status-dot"></span>
          {{ (user() || userTemplate).status }}
        </div>
      </div>
    </shimmer>
  </section>

  <!-- Stats Section -->
  <section class="dashboard-section">
    <shimmer
      [loading]="loadingStats()"
      shimmerColor="rgba(16, 185, 129, 0.4)"
      backgroundColor="rgba(16, 185, 129, 0.1)"
    >
      <div class="stats-grid">
        @for (stat of stats() || statsTemplate; track stat.label) {
          <div class="stat-card">
            <p class="stat-label">{{ stat.label }}</p>
            <h3 class="stat-value">{{ stat.value }}</h3>
            <span
              class="stat-change"
              [class.up]="stat.trend === 'up'"
              [class.down]="stat.trend === 'down'"
            >
              {{ stat.trend === 'up' ? '↑' : '↓' }} {{ stat.change }}
            </span>
          </div>
        }
      </div>
    </shimmer>
  </section>

  <!-- Notifications Panel (Simulated lazy load) -->
  <section class="dashboard-section suspense-section">
    <div class="suspense-label">⚡ Simulated Lazy Loading</div>
    <shimmer
      [loading]="loadingNotifications()"
      shimmerColor="rgba(251, 191, 36, 0.4)"
      backgroundColor="rgba(251, 191, 36, 0.1)"
    >
      <div class="notifications-panel">
        <h3 class="section-title">🔔 Notifications</h3>
        <div class="notifications-list">
          @for (notif of notifications() || notificationsTemplate; track notif.id) {
            <div class="notification-item" [class]="notif.type">
              <div class="notification-header">
                <span class="notification-title">{{ notif.title }}</span>
                <span class="notification-time">{{ notif.time }}</span>
              </div>
              <p class="notification-message">{{ notif.message }}</p>
            </div>
          }
        </div>
      </div>
    </shimmer>
  </section>

  <!-- Orders Table Section -->
  <section class="dashboard-section">
    <shimmer [loading]="loadingOrders()">
      <div class="orders-table-container">
        <h3 class="section-title">Recent Orders</h3>
        <table class="orders-table">
          <thead>
            <tr>
              <th style="width: 25%">Customer</th>
              <th style="width: 40%">Product</th>
              <th style="width: 20%">Amount</th>
              <th style="width: 15%">Status</th>
            </tr>
          </thead>
          <tbody>
            @for (order of orders() || ordersTemplate; track order.id) {
              <tr>
                <td style="font-weight: 500">{{ order.customer }}</td>
                <td style="color: #888">{{ order.product }}</td>
                <td style="font-weight: 600">{{ order.amount }}</td>
                <td>
                  <span
                    class="order-status"
                    [class.delivered]="order.status === 'Delivered'"
                    [class.processing]="order.status === 'Processing'"
                    [class.cancelled]="order.status === 'Cancelled'"
                  >
                    {{ order.status }}
                  </span>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </shimmer>
  </section>

  <!-- Revenue Chart Section -->
  <section class="dashboard-section">
    <shimmer [loading]="loadingChart()">
      <div class="revenue-chart">
        <h3 class="section-title">Weekly Revenue</h3>
        <div class="chart-container">
          <!-- Simple SVG bar chart -->
          <svg width="100%" height="250" style="overflow: visible" viewBox="0 0 700 250">
            @for (point of chartData() || chartTemplate; track point.name; let i = $index) {
              <g [attr.transform]="'translate(' + (i * 100 + 35) + ', 0)'">
                <!-- Revenue bar -->
                <rect
                  x="0"
                  [attr.y]="250 - point.revenue / 100"
                  width="42"
                  [attr.height]="point.revenue / 100"
                  fill="#14b8a6"
                  opacity="0.6"
                  rx="4"
                />
                <!-- Orders bar -->
                <rect
                  x="49"
                  [attr.y]="250 - point.orders * 2.5"
                  width="42"
                  [attr.height]="point.orders * 2.5"
                  fill="#06b6d4"
                  opacity="0.6"
                  rx="4"
                />
                <!-- Label -->
                <text
                  x="42"
                  y="245"
                  fill="rgba(255,255,255,0.5)"
                  font-size="12"
                  text-anchor="middle"
                >
                  {{ point.name }}
                </text>
              </g>
            }
          </svg>
        </div>
      </div>
    </shimmer>
  </section>

  <!-- Main Content Grid -->
  <div class="content-grid">
    <!-- Transactions -->
    <section class="dashboard-section">
      <shimmer [loading]="loadingTransactions()">
        <div class="transactions-list">
          <h3 class="section-title">Recent Transactions</h3>
          <div class="transactions">
            @for (tx of transactions() || transactionsTemplate; track tx.id) {
              <div class="transaction-item">
                <div class="tx-info">
                  <p class="tx-description">{{ tx.description }}</p>
                  <span class="tx-date">{{ tx.date }}</span>
                </div>
                <div class="tx-right">
                  <span class="tx-amount">{{ tx.amount }}</span>
                  <span class="tx-status" [class]="tx.status">{{ tx.status }}</span>
                </div>
              </div>
            }
          </div>
        </div>
      </shimmer>
    </section>

    <!-- Right Sidebar -->
    <div class="sidebar">
      <!-- Activity Feed -->
      <section class="dashboard-section">
        <shimmer [loading]="loadingActivity()">
          <div class="activity-feed">
            <h3 class="section-title">Recent Activity</h3>
            <div class="activities">
              @for (act of activity() || activityTemplate; track act.id) {
                <div class="activity-item">
                  <div class="activity-dot"></div>
                  <div class="activity-content">
                    <p>
                      <strong>{{ act.user }}</strong> {{ act.action }}
                      <span class="activity-target">{{ act.target }}</span>
                    </p>
                    <span class="activity-time">{{ act.time }}</span>
                  </div>
                </div>
              }
            </div>
          </div>
        </shimmer>
      </section>

      <!-- Team Members -->
      <section class="dashboard-section">
        <shimmer [loading]="loadingTeam()">
          <div class="team-members">
            <h3 class="section-title">Team</h3>
            <div class="members-grid">
              @for (member of team() || teamTemplate; track member.id) {
                <div class="member-card">
                  <img [src]="member.avatar" [alt]="member.name" class="member-avatar" />
                  <p class="member-name">{{ member.name }}</p>
                  <span class="member-role">{{ member.role }}</span>
                </div>
              }
            </div>
          </div>
        </shimmer>
      </section>
    </div>
  </div>

  <!-- Context API Example -->
  <section class="dashboard-section context-section">
    <h3 class="section-title">🎨 Config Provider Example (Custom Theme)</h3>
    <p>This section uses custom shimmer configuration to apply a global blue theme.</p>

    <shimmer
      [loading]="loadingContextExample()"
      shimmerColor="rgba(56, 189, 248, 0.4)"
      backgroundColor="rgba(56, 189, 248, 0.1)"
      [duration]="3"
      [fallbackBorderRadius]="16"
    >
      <div class="members-grid">
        @for (member of contextData() || teamTemplate.slice(0, 2); track member.id) {
          <div class="member-card">
            <div
              style="
                width: 40px;
                height: 40px;
                border-radius: 50%;
                background: #333;
                margin-bottom: 8px;
              "
            ></div>
            <p class="member-name">{{ member.name }}</p>
            <span class="member-role">{{ member.role }}</span>
          </div>
        }
      </div>
    </shimmer>
  </section>

  <!-- HTML Attribute Controls Demo -->
  <section class="dashboard-section" style="margin-top: 2rem;">
    <h3 class="section-title">🎛️ HTML Attribute Controls</h3>
    <p class="attributes-demo-description">
      Use <code>data-shimmer-ignore</code> to exclude an element and its children entirely.
      Use <code>data-shimmer-no-children</code> to capture an element as a single shimmer block.
    </p>
    <shimmer [loading]="loadingAttributesDemo()">
      <div class="attributes-demo-grid">
        @for (card of attributesDemoData() || metricCardsTemplate; track card.id; let i = $index) {
          <div class="attr-card">
            <div class="attr-card-header">
              <span class="attr-card-title">{{ card.title }}</span>
              <!-- data-shimmer-ignore: badge is excluded from shimmer entirely -->
              @if (card.isLive) {
                <span class="live-badge" data-shimmer-ignore="">● LIVE</span>
              }
            </div>

            <!-- data-shimmer-no-children (card 2 only): whole block is one shimmer rect -->
            @if (i === 1) {
              <div class="attr-card-metric" data-shimmer-no-children="">
                <span class="attr-metric-value">{{ card.value }}</span>
                <span class="attr-metric-change" [class.up]="card.trend === 'up'" [class.down]="card.trend === 'down'">
                  {{ card.trend === 'up' ? '↑' : '↓' }} {{ card.change }}
                </span>
              </div>
            } @else {
              <div class="attr-card-metric">
                <span class="attr-metric-value">{{ card.value }}</span>
                <span class="attr-metric-change" [class.up]="card.trend === 'up'" [class.down]="card.trend === 'down'">
                  {{ card.trend === 'up' ? '↑' : '↓' }} {{ card.change }}
                </span>
              </div>
            }

            <p class="attr-card-note">
              @if (i === 0) { "LIVE" badge skipped via data-shimmer-ignore }
              @else if (i === 1) { Metric block is one shimmer via data-shimmer-no-children }
              @else { Normal shimmer (no attributes) }
            </p>
          </div>
        }
      </div>
    </shimmer>
  </section>

  <!-- Footer -->
  <footer class="dashboard-footer">
    <p>
      Each section loads independently with its own shimmer effect.
      <br />
      Angular signals track loading states for reactive shimmer updates.
    </p>
  </footer>
</div>
