// examples/solid-example/src/App.tsx
import { createSignal, createEffect, onCleanup, For, type Component } from 'solid-js';
import { Shimmer, ShimmerProvider } from '@shimmer-from-structure/solid';
import './App.css';

// =============================================================================
// TYPES
// =============================================================================

interface User {
  name: string;
  email: string;
  role: string;
  avatar: string;
  status: 'online' | 'away' | 'offline';
}

interface StatCard {
  label: string;
  value: string;
  change: string;
  trend: 'up' | 'down';
}

interface Transaction {
  id: string;
  description: string;
  amount: string;
  date: string;
  status: 'completed' | 'pending' | 'failed';
}

interface TeamMember {
  id: string;
  name: string;
  role: string;
  avatar: string;
}

interface MetricCard {
  id: string;
  title: string;
  value: string;
  change: string;
  trend: 'up' | 'down';
  isLive: boolean;
}

// =============================================================================
// TEMPLATE DATA (Mock data for shimmer skeletons)
// =============================================================================

const userTemplate: User = {
  name: 'Sarah Johnson',
  email: 'sarah.johnson@company.com',
  role: 'Software Engineer',
  avatar: 'https://placeholder.photo/64',
  status: 'offline',
};

const statsTemplate: StatCard[] = [
  { label: 'Total Revenue', value: '$00,000', change: '+0.0%', trend: 'up' },
  { label: 'Active Users', value: '0,000', change: '+0.0%', trend: 'up' },
  { label: 'Conversion', value: '0.0%', change: '-0.0%', trend: 'down' },
  { label: 'Avg. Order', value: '$000', change: '+0.0%', trend: 'up' },
];

const transactionsTemplate: Transaction[] = [
  {
    id: '1',
    description: 'Loading transaction...',
    amount: '$0.00',
    date: 'Jan 00',
    status: 'pending',
  },
  {
    id: '2',
    description: 'Loading transaction...',
    amount: '$0.00',
    date: 'Jan 00',
    status: 'pending',
  },
  {
    id: '3',
    description: 'Loading transaction...',
    amount: '$0.00',
    date: 'Jan 00',
    status: 'pending',
  },
  {
    id: '4',
    description: 'Loading transaction...',
    amount: '$0.00',
    date: 'Jan 00',
    status: 'pending',
  },
];

const teamTemplate: TeamMember[] = [
  { id: '1', name: 'Loading...', role: 'Role', avatar: 'https://placeholder.photo/40' },
  { id: '2', name: 'Loading...', role: 'Lead Developer', avatar: 'https://placeholder.photo/40' },
  { id: '3', name: 'Loading...', role: 'Role', avatar: 'https://placeholder.photo/40' },
  {
    id: '4',
    name: 'Loading...',
    role: 'Backend Developer',
    avatar: 'https://placeholder.photo/40',
  },
];

const metricCardsTemplate: MetricCard[] = [
  { id: '1', title: 'API Requests', value: '0.0k/s', change: '+0.0%', trend: 'up', isLive: true },
  { id: '2', title: 'Error Rate', value: '0.00%', change: '-0.00%', trend: 'up', isLive: true },
  { id: '3', title: 'Uptime', value: '00.00%', change: '+0.00%', trend: 'up', isLive: false },
];

const realMetricCards: MetricCard[] = [
  { id: '1', title: 'API Requests', value: '12.4k/s', change: '+3.2%', trend: 'up', isLive: true },
  { id: '2', title: 'Error Rate', value: '0.08%', change: '-0.01%', trend: 'up', isLive: true },
  { id: '3', title: 'Uptime', value: '99.98%', change: '+0.01%', trend: 'up', isLive: false },
];

// =============================================================================
// REAL DATA (Simulated API responses)
// =============================================================================

const realUser: User = {
  name: 'Sarah Johnson',
  email: 'sarah.johnson@company.com',
  role: 'Product Manager',
  avatar: 'https://i.pravatar.cc/64?img=5',
  status: 'online',
};

const realStats: StatCard[] = [
  { label: 'Total Revenue', value: '$48,352', change: '+12.5%', trend: 'up' },
  { label: 'Active Users', value: '2,847', change: '+8.2%', trend: 'up' },
  { label: 'Conversion', value: '3.24%', change: '-0.4%', trend: 'down' },
  { label: 'Avg. Order', value: '$284', change: '+5.7%', trend: 'up' },
];

const realTransactions: Transaction[] = [
  {
    id: '1',
    description: 'Premium Subscription',
    amount: '$99.00',
    date: 'Jan 20',
    status: 'completed',
  },
  {
    id: '2',
    description: 'API Credits Purchase',
    amount: '$250.00',
    date: 'Jan 19',
    status: 'completed',
  },
  {
    id: '3',
    description: 'Team License Upgrade',
    amount: '$499.00',
    date: 'Jan 18',
    status: 'pending',
  },
  { id: '4', description: 'Support Add-on', amount: '$49.00', date: 'Jan 17', status: 'completed' },
];

const realTeam: TeamMember[] = [
  { id: '1', name: 'Mike Chen', role: 'Lead Developer', avatar: 'https://i.pravatar.cc/40?img=11' },
  { id: '2', name: 'Emily Davis', role: 'UX Designer', avatar: 'https://i.pravatar.cc/40?img=9' },
  {
    id: '3',
    name: 'Alex Rivera',
    role: 'Backend Engineer',
    avatar: 'https://i.pravatar.cc/40?img=12',
  },
  { id: '4', name: 'Jordan Lee', role: 'DevOps', avatar: 'https://i.pravatar.cc/40?img=15' },
];

// =============================================================================
// COMPONENTS
// =============================================================================

const UserProfile: Component<{ user: User }> = (props) => (
  <div class="user-profile">
    <img src={props.user.avatar} alt={props.user.name} class="user-avatar" />
    <div class="user-info">
      <h2>{props.user.name}</h2>
      <p class="user-email">{props.user.email}</p>
      <span class={`user-status ${props.user.status}`}>{props.user.role}</span>
    </div>
    <div class={`status-indicator ${props.user.status}`}>
      <span class="status-dot"></span>
      {props.user.status}
    </div>
  </div>
);

const StatsGrid: Component<{ stats: StatCard[] }> = (props) => (
  <div class="stats-grid">
    <For each={props.stats}>
      {(stat) => (
        <div class="stat-card">
          <p class="stat-label">{stat.label}</p>
          <h3 class="stat-value">{stat.value}</h3>
          <span class={`stat-change ${stat.trend}`}>
            {stat.trend === 'up' ? '↑' : '↓'} {stat.change}
          </span>
        </div>
      )}
    </For>
  </div>
);

const TransactionsList: Component<{ transactions: Transaction[] }> = (props) => (
  <div class="transactions-list">
    <h3 class="section-title">Recent Transactions</h3>
    <div class="transactions">
      <For each={props.transactions}>
        {(tx) => (
          <div class="transaction-item">
            <div class="tx-info">
              <p class="tx-description">{tx.description}</p>
              <span class="tx-date">{tx.date}</span>
            </div>
            <div class="tx-right">
              <span class="tx-amount">{tx.amount}</span>
              <span class={`tx-status ${tx.status}`}>{tx.status}</span>
            </div>
          </div>
        )}
      </For>
    </div>
  </div>
);

const TeamMembers: Component<{ members: TeamMember[] }> = (props) => (
  <div class="team-members">
    <h3 class="section-title">Team</h3>
    <div class="members-grid">
      <For each={props.members}>
        {(member) => (
          <div class="member-card">
            <img src={member.avatar} alt={member.name} class="member-avatar" />
            <p class="member-name">{member.name}</p>
            <span class="member-role">{member.role}</span>
          </div>
        )}
      </For>
    </div>
  </div>
);

const AttributesDemo: Component<{ cards: MetricCard[] }> = (props) => (
  <div class="attributes-demo-grid">
    <For each={props.cards}>
      {(card, i) => (
        <div class="attr-card">
          <div class="attr-card-header">
            <span class="attr-card-title">{card.title}</span>
            {card.isLive && (
              // data-shimmer-ignore: this badge is completely excluded from shimmer measurement
              <span class="live-badge" data-shimmer-ignore="">
                ● LIVE
              </span>
            )}
          </div>

          {i() === 1 ? (
            // data-shimmer-no-children: the whole block is captured as one shimmer rect
            // instead of measuring the value and change span individually
            <div class="attr-card-metric" data-shimmer-no-children="">
              <span class="attr-metric-value">{card.value}</span>
              <span class={`attr-metric-change ${card.trend}`}>
                {card.trend === 'up' ? '↑' : '↓'} {card.change}
              </span>
            </div>
          ) : (
            <div class="attr-card-metric">
              <span class="attr-metric-value">{card.value}</span>
              <span class={`attr-metric-change ${card.trend}`}>
                {card.trend === 'up' ? '↑' : '↓'} {card.change}
              </span>
            </div>
          )}

          <p class="attr-card-note">
            {i() === 0
              ? '"LIVE" badge skipped via data-shimmer-ignore'
              : i() === 1
                ? 'Metric block is one shimmer via data-shimmer-no-children'
                : 'Normal shimmer (no attributes)'}
          </p>
        </div>
      )}
    </For>
  </div>
);

// =============================================================================
// MAIN APP
// =============================================================================

const App: Component = () => {
  // Independent loading states for each section
  const [loadingUser, setLoadingUser] = createSignal(true);
  const [loadingStats, setLoadingStats] = createSignal(true);
  const [loadingTransactions, setLoadingTransactions] = createSignal(true);
  const [loadingTeam, setLoadingTeam] = createSignal(true);

  // Data states
  const [user, setUser] = createSignal<User | null>(null);
  const [stats, setStats] = createSignal<StatCard[] | null>(null);
  const [transactions, setTransactions] = createSignal<Transaction[] | null>(null);
  const [team, setTeam] = createSignal<TeamMember[] | null>(null);

  // Context Example State
  const [loadingContextExample, setLoadingContextExample] = createSignal(true);
  const [contextData, setContextData] = createSignal<TeamMember[] | null>(null);

  // Attribute Controls Demo State
  const [loadingAttributesDemo, setLoadingAttributesDemo] = createSignal(true);
  const [attributesDemoData, setAttributesDemoData] = createSignal<MetricCard[] | null>(null);

  // Simulate independent API calls with different response times
  createEffect(() => {
    const userTimer = setTimeout(() => {
      setUser(realUser);
      setLoadingUser(false);
    }, 9800);

    const statsTimer = setTimeout(() => {
      setStats(realStats);
      setLoadingStats(false);
    }, 6200);

    const teamTimer = setTimeout(() => {
      setTeam(realTeam);
      setLoadingTeam(false);
    }, 9600);

    const transactionsTimer = setTimeout(() => {
      setTransactions(realTransactions);
      setLoadingTransactions(false);
    }, 2500);

    const contextTimer = setTimeout(() => {
      setContextData(realTeam.slice(0, 2));
      setLoadingContextExample(false);
    }, 4000);

    const attributesTimer = setTimeout(() => {
      setAttributesDemoData(realMetricCards);
      setLoadingAttributesDemo(false);
    }, 6000);

    onCleanup(() => {
      clearTimeout(userTimer);
      clearTimeout(statsTimer);
      clearTimeout(teamTimer);
      clearTimeout(transactionsTimer);
      clearTimeout(contextTimer);
      clearTimeout(attributesTimer);
    });
  });

  // Reset all data
  const handleReload = () => {
    setLoadingUser(true);
    setLoadingStats(true);
    setLoadingTransactions(true);
    setLoadingTeam(true);
    setLoadingContextExample(true);
    setLoadingAttributesDemo(true);
    setUser(null);
    setStats(null);
    setTransactions(null);
    setTeam(null);
    setContextData(null);
    setAttributesDemoData(null);

    setTimeout(() => {
      setUser(realUser);
      setLoadingUser(false);
    }, 800);
    setTimeout(() => {
      setStats(realStats);
      setLoadingStats(false);
    }, 1200);
    setTimeout(() => {
      setTeam(realTeam);
      setLoadingTeam(false);
    }, 1600);
    setTimeout(() => {
      setTransactions(realTransactions);
      setLoadingTransactions(false);
    }, 2500);
    setTimeout(() => {
      setContextData(realTeam.slice(0, 2));
      setLoadingContextExample(false);
    }, 4000);
    setTimeout(() => {
      setAttributesDemoData(realMetricCards);
      setLoadingAttributesDemo(false);
    }, 6000);
  };

  return (
    <div class="dashboard">
      {/* Header */}
      <header class="dashboard-header">
        <div class="header-content">
          <h1>Shimmer From Structure - SolidJS</h1>
          <p>Real-world dashboard demo with independent loading states</p>
        </div>
        <button class="reload-btn" onClick={handleReload}>
          ↻ Reload Demo
        </button>
      </header>

      {/* User Profile Section */}
      <section class="dashboard-section">
        <Shimmer loading={loadingUser()}>
          <UserProfile user={user() || userTemplate} />
        </Shimmer>
      </section>

      {/* Stats Section */}
      <section class="dashboard-section">
        <Shimmer loading={loadingStats()}>
          <StatsGrid stats={stats() || statsTemplate} />
        </Shimmer>
      </section>

      {/* Main Content Grid */}
      <div class="content-grid">
        {/* Transactions */}
        <section class="dashboard-section">
          <Shimmer loading={loadingTransactions()}>
            <TransactionsList transactions={transactions() || transactionsTemplate} />
          </Shimmer>
        </section>

        {/* Sidebar */}
        <div class="sidebar">
          {/* Team Members */}
          <section class="dashboard-section">
            <Shimmer loading={loadingTeam()}>
              <TeamMembers members={team() || teamTemplate} />
            </Shimmer>
          </section>

          {/* Context Example - Custom Theme */}
          <section
            class="dashboard-section"
            style={{ border: '1px solid rgba(139, 92, 246, 0.3)' }}
          >
            <div
              style={{
                position: 'absolute',
                top: '-10px',
                left: '16px',
                background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
                padding: '2px 12px',
                'font-size': '0.75rem',
                'font-weight': '600',
                color: '#a78bfa',
                'border-radius': '4px',
                'text-transform': 'uppercase',
                'letter-spacing': '0.5px',
              }}
            >
              ⚡ Custom Theme Example
            </div>
            <ShimmerProvider
              config={{
                shimmerColor: 'rgba(139, 92, 246, 0.5)',
                backgroundColor: 'rgba(139, 92, 246, 0.15)',
                duration: 2,
                fallbackBorderRadius: 8,
              }}
            >
              <Shimmer loading={loadingContextExample()}>
                <TeamMembers members={contextData() || teamTemplate.slice(0, 2)} />
              </Shimmer>
            </ShimmerProvider>
          </section>
        </div>
      </div>

      {/* HTML Attribute Controls Demo */}
      <section class="dashboard-section" style={{ 'margin-top': '2rem' }}>
        <h3 class="section-title">🎛️ HTML Attribute Controls</h3>
        <p class="attributes-demo-description">
          Use <code>data-shimmer-ignore</code> to exclude an element and its children entirely from
          shimmer. Use <code>data-shimmer-no-children</code> to capture an element as a single
          shimmer block instead of recursing into its children.
        </p>
        <Shimmer loading={loadingAttributesDemo()}>
          <AttributesDemo cards={attributesDemoData() || metricCardsTemplate} />
        </Shimmer>
      </section>

      {/* Footer */}
      <footer class="dashboard-footer">
        <p>
          🎯 This demo showcases <code>@shimmer-from-structure/solid</code> adapter
          <br />
          Built with SolidJS primitives: createSignal, createEffect, Show, For, and Context API
        </p>
      </footer>
    </div>
  );
};

export default App;

// examples/angular-example/src/app/app.component.ts
import { Component, signal, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ShimmerComponent } from '@shimmer-from-structure/angular';

// =============================================================================
// TYPES
// =============================================================================

interface User {
  name: string;
  email: string;
  role: string;
  avatar: string;
  status: 'online' | 'away' | 'offline';
}

interface StatCard {
  label: string;
  value: string;
  change: string;
  trend: 'up' | 'down';
}

interface Transaction {
  id: string;
  description: string;
  amount: string;
  date: string;
  status: 'completed' | 'pending' | 'failed';
}

interface ActivityItem {
  id: string;
  user: string;
  action: string;
  target: string;
  time: string;
}

interface TeamMember {
  id: string;
  name: string;
  role: string;
  avatar: string;
}

interface ChartDataPoint {
  name: string;
  revenue: number;
  orders: number;
}

interface Order {
  id: string;
  customer: string;
  product: string;
  amount: string;
  status: 'Delivered' | 'Processing' | 'Cancelled';
}

interface MetricCard {
  id: string;
  title: string;
  value: string;
  change: string;
  trend: 'up' | 'down';
  isLive: boolean;
}

interface Notification {
  id: string;
  title: string;
  message: string;
  time: string;
  type: 'info' | 'success' | 'warning';
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, ShimmerComponent],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit, OnDestroy {
  // Loading states
  loadingUser = signal(true);
  loadingStats = signal(true);
  loadingTransactions = signal(true);
  loadingActivity = signal(true);
  loadingTeam = signal(true);
  loadingOrders = signal(true);
  loadingChart = signal(true);
  loadingNotifications = signal(true);
  loadingContextExample = signal(true);
  loadingAttributesDemo = signal(true);

  // Data signals
  user = signal<User | null>(null);
  stats = signal<StatCard[] | null>(null);
  transactions = signal<Transaction[] | null>(null);
  orders = signal<Order[] | null>(null);
  activity = signal<ActivityItem[] | null>(null);
  team = signal<TeamMember[] | null>(null);
  chartData = signal<ChartDataPoint[] | null>(null);
  notifications = signal<Notification[] | null>(null);
  contextData = signal<TeamMember[] | null>(null);
  attributesDemoData = signal<MetricCard[] | null>(null);

  // Template data
  metricCardsTemplate: MetricCard[] = [
    { id: '1', title: 'API Requests', value: '0.0k/s', change: '+0.0%', trend: 'up', isLive: true },
    { id: '2', title: 'Error Rate', value: '0.00%', change: '-0.00%', trend: 'up', isLive: true },
    { id: '3', title: 'Uptime', value: '00.00%', change: '+0.00%', trend: 'up', isLive: false },
  ];

  realMetricCards: MetricCard[] = [
    {
      id: '1',
      title: 'API Requests',
      value: '12.4k/s',
      change: '+3.2%',
      trend: 'up',
      isLive: true,
    },
    { id: '2', title: 'Error Rate', value: '0.08%', change: '-0.01%', trend: 'up', isLive: true },
    { id: '3', title: 'Uptime', value: '99.98%', change: '+0.01%', trend: 'up', isLive: false },
  ];

  userTemplate: User = {
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'Software Engineer',
    avatar: 'https://placeholder.photo/64',
    status: 'offline',
  };

  statsTemplate: StatCard[] = [
    { label: 'Total Revenue', value: '$00,000', change: '+0.0%', trend: 'up' },
    { label: 'Active Users', value: '0,000', change: '+0.0%', trend: 'up' },
    { label: 'Conversion', value: '0.0%', change: '-0.0%', trend: 'down' },
    { label: 'Avg. Order', value: '$000', change: '+0.0%', trend: 'up' },
  ];

  transactionsTemplate: Transaction[] = [
    {
      id: '1',
      description: 'Loading transaction...',
      amount: '$0.00',
      date: 'Jan 00',
      status: 'pending',
    },
    {
      id: '2',
      description: 'Loading transaction...',
      amount: '$0.00',
      date: 'Jan 00',
      status: 'pending',
    },
    {
      id: '3',
      description: 'Loading transaction...',
      amount: '$0.00',
      date: 'Jan 00',
      status: 'pending',
    },
    {
      id: '4',
      description: 'Loading transaction...',
      amount: '$0.00',
      date: 'Jan 00',
      status: 'pending',
    },
  ];

  activityTemplate: ActivityItem[] = [
    { id: '1', user: 'Loading...', action: 'performed', target: 'an action', time: '0m ago' },
    { id: '2', user: 'Loading...', action: 'performed', target: 'an action', time: '0m ago' },
    { id: '3', user: 'Loading...', action: 'performed', target: 'an action', time: '0m ago' },
  ];

  teamTemplate: TeamMember[] = [
    { id: '1', name: 'Loading...', role: 'Role', avatar: 'https://placeholder.photo/40' },
    {
      id: '2',
      name: 'Loading...',
      role: 'Lead Developer',
      avatar: 'https://placeholder.photo/40',
    },
    { id: '3', name: 'Loading...', role: 'Role', avatar: 'https://placeholder.photo/40' },
    {
      id: '4',
      name: 'Loading...',
      role: 'Backend Developer',
      avatar: 'https://placeholder.photo/40',
    },
  ];

  ordersTemplate: Order[] = [
    {
      id: '1',
      customer: 'Loading Name...',
      product: 'Loading Product...',
      amount: '$000.00',
      status: 'Processing',
    },
    {
      id: '2',
      customer: 'Loading Name...',
      product: 'Loading Product...',
      amount: '$000.00',
      status: 'Processing',
    },
    {
      id: '3',
      customer: 'Loading Name...',
      product: 'Loading Product...',
      amount: '$000.00',
      status: 'Processing',
    },
    {
      id: '4',
      customer: 'Loading Name...',
      product: 'Loading Product...',
      amount: '$000.00',
      status: 'Processing',
    },
    {
      id: '5',
      customer: 'Loading Name...',
      product: 'Loading Product...',
      amount: '$000.00',
      status: 'Processing',
    },
  ];

  chartTemplate: ChartDataPoint[] = [
    { name: 'Mon', revenue: 3000, orders: 30 },
    { name: 'Tue', revenue: 4500, orders: 45 },
    { name: 'Wed', revenue: 3800, orders: 38 },
    { name: 'Thu', revenue: 5200, orders: 52 },
    { name: 'Fri', revenue: 6100, orders: 61 },
    { name: 'Sat', revenue: 7000, orders: 70 },
    { name: 'Sun', revenue: 5500, orders: 55 },
  ];

  notificationsTemplate: Notification[] = [
    {
      id: '1',
      title: 'Loading...',
      message: 'Notification message loading...',
      time: '0m',
      type: 'info',
    },
    {
      id: '2',
      title: 'Loading...',
      message: 'Notification message loading...',
      time: '0m',
      type: 'info',
    },
    {
      id: '3',
      title: 'Loading...',
      message: 'Notification message loading...',
      time: '0m',
      type: 'info',
    },
  ];

  // Real data
  realUser: User = {
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'Product Manager',
    avatar: 'https://i.pravatar.cc/64?img=5',
    status: 'online',
  };

  realStats: StatCard[] = [
    { label: 'Total Revenue', value: '$48,352', change: '+12.5%', trend: 'up' },
    { label: 'Active Users', value: '2,847', change: '+8.2%', trend: 'up' },
    { label: 'Conversion', value: '3.24%', change: '-0.4%', trend: 'down' },
    { label: 'Avg. Order', value: '$284', change: '+5.7%', trend: 'up' },
  ];

  realTransactions: Transaction[] = [
    {
      id: '1',
      description: 'Premium Subscription',
      amount: '$99.00',
      date: 'Jan 20',
      status: 'completed',
    },
    {
      id: '2',
      description: 'API Credits Purchase',
      amount: '$250.00',
      date: 'Jan 19',
      status: 'completed',
    },
    {
      id: '3',
      description: 'Team License Upgrade',
      amount: '$499.00',
      date: 'Jan 18',
      status: 'pending',
    },
    {
      id: '4',
      description: 'Support Add-on',
      amount: '$49.00',
      date: 'Jan 17',
      status: 'completed',
    },
  ];

  realActivity: ActivityItem[] = [
    {
      id: '1',
      user: 'Mike Chen',
      action: 'deployed',
      target: 'v2.4.1 to production',
      time: '5m ago',
    },
    {
      id: '2',
      user: 'Emily Davis',
      action: 'approved',
      target: 'design review for Dashboard',
      time: '23m ago',
    },
    { id: '3', user: 'Alex Rivera', action: 'commented on', target: 'Issue #847', time: '1h ago' },
  ];

  realTeam: TeamMember[] = [
    {
      id: '1',
      name: 'Mike Chen',
      role: 'Lead Developer',
      avatar: 'https://i.pravatar.cc/40?img=11',
    },
    { id: '2', name: 'Emily Davis', role: 'UX Designer', avatar: 'https://i.pravatar.cc/40?img=9' },
    {
      id: '3',
      name: 'Alex Rivera',
      role: 'Backend Engineer',
      avatar: 'https://i.pravatar.cc/40?img=12',
    },
    { id: '4', name: 'Jordan Lee', role: 'DevOps', avatar: 'https://i.pravatar.cc/40?img=15' },
  ];

  realOrders: Order[] = [
    {
      id: '101',
      customer: 'Alice Freeman',
      product: 'Pro Plan (Monthly)',
      amount: '$29.00',
      status: 'Delivered',
    },
    {
      id: '102',
      customer: 'Bob Smith',
      product: 'Enterprise License',
      amount: '$499.00',
      status: 'Processing',
    },
    {
      id: '103',
      customer: 'Charlie Brown',
      product: 'Basic Plan (Yearly)',
      amount: '$99.00',
      status: 'Cancelled',
    },
    {
      id: '104',
      customer: 'David Wilson',
      product: 'Pro Plan (Monthly)',
      amount: '$29.00',
      status: 'Delivered',
    },
    {
      id: '105',
      customer: 'Eva Green',
      product: 'Consulting Hour',
      amount: '$150.00',
      status: 'Delivered',
    },
  ];

  realChartData: ChartDataPoint[] = [
    { name: 'Mon', revenue: 4200, orders: 42 },
    { name: 'Tue', revenue: 5800, orders: 58 },
    { name: 'Wed', revenue: 4900, orders: 49 },
    { name: 'Thu', revenue: 7200, orders: 72 },
    { name: 'Fri', revenue: 8400, orders: 84 },
    { name: 'Sat', revenue: 9100, orders: 91 },
    { name: 'Sun', revenue: 6800, orders: 68 },
  ];

  realNotifications: Notification[] = [
    {
      id: '1',
      title: 'New Comment',
      message: 'Sarah commented on your pull request #42',
      time: '2m',
      type: 'info',
    },
    {
      id: '2',
      title: 'Build Passed',
      message: 'CI pipeline completed successfully',
      time: '15m',
      type: 'success',
    },
    {
      id: '3',
      title: 'Security Alert',
      message: 'New login detected from Safari on macOS',
      time: '1h',
      type: 'warning',
    },
  ];

  private timeouts: number[] = [];

  ngOnInit() {
    console.log('AppComponent ngOnInit called');
    console.log('Initial loading states:', {
      user: this.loadingUser(),
      stats: this.loadingStats(),
      transactions: this.loadingTransactions(),
    });
    this.loadData();
  }

  ngOnDestroy() {
    this.timeouts.forEach(clearTimeout);
  }

  loadData() {
    console.log('loadData() called - setting up timeouts');

    // User loads first (fast)
    this.timeouts.push(
      window.setTimeout(() => {
        console.log('User timeout fired - setting loading to false');
        this.user.set(this.realUser);
        this.loadingUser.set(false);
        console.log('loadingUser is now:', this.loadingUser());
      }, 4800)
    );

    // Stats load second
    this.timeouts.push(
      window.setTimeout(() => {
        this.stats.set(this.realStats);
        this.loadingStats.set(false);
      }, 8200)
    );

    // Chart loads third
    this.timeouts.push(
      window.setTimeout(() => {
        this.chartData.set(this.realChartData);
        this.loadingChart.set(false);
      }, 5400)
    );

    // Team loads fourth
    this.timeouts.push(
      window.setTimeout(() => {
        this.team.set(this.realTeam);
        this.loadingTeam.set(false);
      }, 4600)
    );

    // Activity loads fifth
    this.timeouts.push(
      window.setTimeout(() => {
        this.activity.set(this.realActivity);
        this.loadingActivity.set(false);
      }, 8000)
    );

    // Transactions load last
    this.timeouts.push(
      window.setTimeout(() => {
        this.transactions.set(this.realTransactions);
        this.loadingTransactions.set(false);
      }, 9500)
    );

    // Orders load independently
    this.timeouts.push(
      window.setTimeout(() => {
        this.orders.set(this.realOrders);
        this.loadingOrders.set(false);
      }, 7800)
    );

    // Notifications (delayed like lazy loading)
    this.timeouts.push(
      window.setTimeout(() => {
        this.notifications.set(this.realNotifications);
        this.loadingNotifications.set(false);
      }, 8000)
    );

    // Context Example loads extra slow
    this.timeouts.push(
      window.setTimeout(() => {
        this.contextData.set(this.realTeam.slice(0, 2));
        this.loadingContextExample.set(false);
      }, 9000)
    );

    // Attribute controls demo
    this.timeouts.push(
      window.setTimeout(() => {
        this.attributesDemoData.set(this.realMetricCards);
        this.loadingAttributesDemo.set(false);
      }, 6000)
    );
  }

  handleReload() {
    // Reset all states
    this.loadingUser.set(true);
    this.loadingStats.set(true);
    this.loadingChart.set(true);
    this.loadingTransactions.set(true);
    this.loadingActivity.set(true);
    this.loadingTeam.set(true);
    this.loadingOrders.set(true);
    this.loadingNotifications.set(true);
    this.loadingContextExample.set(true);
    this.loadingAttributesDemo.set(true);

    this.user.set(null);
    this.stats.set(null);
    this.chartData.set(null);
    this.transactions.set(null);
    this.orders.set(null);
    this.activity.set(null);
    this.team.set(null);
    this.notifications.set(null);
    this.contextData.set(null);
    this.attributesDemoData.set(null);

    // Clear existing timeouts
    this.timeouts.forEach(clearTimeout);
    this.timeouts = [];

    // Reload data
    this.loadData();
  }

  getChartHeight(data: ChartDataPoint[], maxHeight: number): number {
    const maxRevenue = Math.max(...data.map((d) => d.revenue));
    return maxHeight * (maxRevenue / 10000);
  }
}

<div class="dashboard">
  <!-- Header -->
  <header class="dashboard-header">
    <div class="header-content">
      <h1>Shimmer From Structure</h1>
      <p>Real-world dashboard demo with independent loading states</p>
    </div>
    <button class="reload-btn" (click)="handleReload()">↻ Reload Demo</button>
  </header>

  <!-- User Profile Section -->
  <section class="dashboard-section">
    <shimmer
      [loading]="loadingUser()"
      shimmerColor="rgba(139, 92, 246, 0.4)"
      backgroundColor="rgba(139, 92, 246, 0.1)"
    >
      <div class="user-profile">
        <img
          [src]="(user() || userTemplate).avatar"
          [alt]="(user() || userTemplate).name"
          class="user-avatar"
        />
        <div class="user-info">
          <h2>{{ (user() || userTemplate).name }}</h2>
          <p class="user-email">{{ (user() || userTemplate).email }}</p>
          <span class="user-status">{{ (user() || userTemplate).role }}</span>
        </div>
        <div
          class="status-indicator"
          [class.online]="(user() || userTemplate).status === 'online'"
          [class.away]="(user() || userTemplate).status === 'away'"
        >
          <span class="status-dot"></span>
          {{ (user() || userTemplate).status }}
        </div>
      </div>
    </shimmer>
  </section>

  <!-- Stats Section -->
  <section class="dashboard-section">
    <shimmer
      [loading]="loadingStats()"
      shimmerColor="rgba(16, 185, 129, 0.4)"
      backgroundColor="rgba(16, 185, 129, 0.1)"
    >
      <div class="stats-grid">
        @for (stat of stats() || statsTemplate; track stat.label) {
          <div class="stat-card">
            <p class="stat-label">{{ stat.label }}</p>
            <h3 class="stat-value">{{ stat.value }}</h3>
            <span
              class="stat-change"
              [class.up]="stat.trend === 'up'"
              [class.down]="stat.trend === 'down'"
            >
              {{ stat.trend === 'up' ? '↑' : '↓' }} {{ stat.change }}
            </span>
          </div>
        }
      </div>
    </shimmer>
  </section>

  <!-- Notifications Panel (Simulated lazy load) -->
  <section class="dashboard-section suspense-section">
    <div class="suspense-label">⚡ Simulated Lazy Loading</div>
    <shimmer
      [loading]="loadingNotifications()"
      shimmerColor="rgba(251, 191, 36, 0.4)"
      backgroundColor="rgba(251, 191, 36, 0.1)"
    >
      <div class="notifications-panel">
        <h3 class="section-title">🔔 Notifications</h3>
        <div class="notifications-list">
          @for (notif of notifications() || notificationsTemplate; track notif.id) {
            <div class="notification-item" [class]="notif.type">
              <div class="notification-header">
                <span class="notification-title">{{ notif.title }}</span>
                <span class="notification-time">{{ notif.time }}</span>
              </div>
              <p class="notification-message">{{ notif.message }}</p>
            </div>
          }
        </div>
      </div>
    </shimmer>
  </section>

  <!-- Orders Table Section -->
  <section class="dashboard-section">
    <shimmer [loading]="loadingOrders()">
      <div class="orders-table-container">
        <h3 class="section-title">Recent Orders</h3>
        <table class="orders-table">
          <thead>
            <tr>
              <th style="width: 25%">Customer</th>
              <th style="width: 40%">Product</th>
              <th style="width: 20%">Amount</th>
              <th style="width: 15%">Status</th>
            </tr>
          </thead>
          <tbody>
            @for (order of orders() || ordersTemplate; track order.id) {
              <tr>
                <td style="font-weight: 500">{{ order.customer }}</td>
                <td style="color: #888">{{ order.product }}</td>
                <td style="font-weight: 600">{{ order.amount }}</td>
                <td>
                  <span
                    class="order-status"
                    [class.delivered]="order.status === 'Delivered'"
                    [class.processing]="order.status === 'Processing'"
                    [class.cancelled]="order.status === 'Cancelled'"
                  >
                    {{ order.status }}
                  </span>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </shimmer>
  </section>

  <!-- Revenue Chart Section -->
  <section class="dashboard-section">
    <shimmer [loading]="loadingChart()">
      <div class="revenue-chart">
        <h3 class="section-title">Weekly Revenue</h3>
        <div class="chart-container">
          <!-- Simple SVG bar chart -->
          <svg width="100%" height="250" style="overflow: visible" viewBox="0 0 700 250">
            @for (point of chartData() || chartTemplate; track point.name; let i = $index) {
              <g [attr.transform]="'translate(' + (i * 100 + 35) + ', 0)'">
                <!-- Revenue bar -->
                <rect
                  x="0"
                  [attr.y]="250 - point.revenue / 100"
                  width="42"
                  [attr.height]="point.revenue / 100"
                  fill="#14b8a6"
                  opacity="0.6"
                  rx="4"
                />
                <!-- Orders bar -->
                <rect
                  x="49"
                  [attr.y]="250 - point.orders * 2.5"
                  width="42"
                  [attr.height]="point.orders * 2.5"
                  fill="#06b6d4"
                  opacity="0.6"
                  rx="4"
                />
                <!-- Label -->
                <text
                  x="42"
                  y="245"
                  fill="rgba(255,255,255,0.5)"
                  font-size="12"
                  text-anchor="middle"
                >
                  {{ point.name }}
                </text>
              </g>
            }
          </svg>
        </div>
      </div>
    </shimmer>
  </section>

  <!-- Main Content Grid -->
  <div class="content-grid">
    <!-- Transactions -->
    <section class="dashboard-section">
      <shimmer [loading]="loadingTransactions()">
        <div class="transactions-list">
          <h3 class="section-title">Recent Transactions</h3>
          <div class="transactions">
            @for (tx of transactions() || transactionsTemplate; track tx.id) {
              <div class="transaction-item">
                <div class="tx-info">
                  <p class="tx-description">{{ tx.description }}</p>
                  <span class="tx-date">{{ tx.date }}</span>
                </div>
                <div class="tx-right">
                  <span class="tx-amount">{{ tx.amount }}</span>
                  <span class="tx-status" [class]="tx.status">{{ tx.status }}</span>
                </div>
              </div>
            }
          </div>
        </div>
      </shimmer>
    </section>

    <!-- Right Sidebar -->
    <div class="sidebar">
      <!-- Activity Feed -->
      <section class="dashboard-section">
        <shimmer [loading]="loadingActivity()">
          <div class="activity-feed">
            <h3 class="section-title">Recent Activity</h3>
            <div class="activities">
              @for (act of activity() || activityTemplate; track act.id) {
                <div class="activity-item">
                  <div class="activity-dot"></div>
                  <div class="activity-content">
                    <p>
                      <strong>{{ act.user }}</strong> {{ act.action }}
                      <span class="activity-target">{{ act.target }}</span>
                    </p>
                    <span class="activity-time">{{ act.time }}</span>
                  </div>
                </div>
              }
            </div>
          </div>
        </shimmer>
      </section>

      <!-- Team Members -->
      <section class="dashboard-section">
        <shimmer [loading]="loadingTeam()">
          <div class="team-members">
            <h3 class="section-title">Team</h3>
            <div class="members-grid">
              @for (member of team() || teamTemplate; track member.id) {
                <div class="member-card">
                  <img [src]="member.avatar" [alt]="member.name" class="member-avatar" />
                  <p class="member-name">{{ member.name }}</p>
                  <span class="member-role">{{ member.role }}</span>
                </div>
              }
            </div>
          </div>
        </shimmer>
      </section>
    </div>
  </div>

  <!-- Context API Example -->
  <section class="dashboard-section context-section">
    <h3 class="section-title">🎨 Config Provider Example (Custom Theme)</h3>
    <p>This section uses custom shimmer configuration to apply a global blue theme.</p>

    <shimmer
      [loading]="loadingContextExample()"
      shimmerColor="rgba(56, 189, 248, 0.4)"
      backgroundColor="rgba(56, 189, 248, 0.1)"
      [duration]="3"
      [fallbackBorderRadius]="16"
    >
      <div class="members-grid">
        @for (member of contextData() || teamTemplate.slice(0, 2); track member.id) {
          <div class="member-card">
            <div
              style="
                width: 40px;
                height: 40px;
                border-radius: 50%;
                background: #333;
                margin-bottom: 8px;
              "
            ></div>
            <p class="member-name">{{ member.name }}</p>
            <span class="member-role">{{ member.role }}</span>
          </div>
        }
      </div>
    </shimmer>
  </section>

  <!-- HTML Attribute Controls Demo -->
  <section class="dashboard-section" style="margin-top: 2rem;">
    <h3 class="section-title">🎛️ HTML Attribute Controls</h3>
    <p class="attributes-demo-description">
      Use <code>data-shimmer-ignore</code> to exclude an element and its children entirely.
      Use <code>data-shimmer-no-children</code> to capture an element as a single shimmer block.
    </p>
    <shimmer [loading]="loadingAttributesDemo()">
      <div class="attributes-demo-grid">
        @for (card of attributesDemoData() || metricCardsTemplate; track card.id; let i = $index) {
          <div class="attr-card">
            <div class="attr-card-header">
              <span class="attr-card-title">{{ card.title }}</span>
              <!-- data-shimmer-ignore: badge is excluded from shimmer entirely -->
              @if (card.isLive) {
                <span class="live-badge" data-shimmer-ignore="">● LIVE</span>
              }
            </div>

            <!-- data-shimmer-no-children (card 2 only): whole block is one shimmer rect -->
            @if (i === 1) {
              <div class="attr-card-metric" data-shimmer-no-children="">
                <span class="attr-metric-value">{{ card.value }}</span>
                <span class="attr-metric-change" [class.up]="card.trend === 'up'" [class.down]="card.trend === 'down'">
                  {{ card.trend === 'up' ? '↑' : '↓' }} {{ card.change }}
                </span>
              </div>
            } @else {
              <div class="attr-card-metric">
                <span class="attr-metric-value">{{ card.value }}</span>
                <span class="attr-metric-change" [class.up]="card.trend === 'up'" [class.down]="card.trend === 'down'">
                  {{ card.trend === 'up' ? '↑' : '↓' }} {{ card.change }}
                </span>
              </div>
            }

            <p class="attr-card-note">
              @if (i === 0) { "LIVE" badge skipped via data-shimmer-ignore }
              @else if (i === 1) { Metric block is one shimmer via data-shimmer-no-children }
              @else { Normal shimmer (no attributes) }
            </p>
          </div>
        }
      </div>
    </shimmer>
  </section>

  <!-- Footer -->
  <footer class="dashboard-footer">
    <p>
      Each section loads independently with its own shimmer effect.
      <br />
      Angular signals track loading states for reactive shimmer updates.
    </p>
  </footer>
</div>
